import { config, validateHaConfig } from "../config.ts";
import { repository, type HaClusterConfigInsert } from "../db/repository.ts";
import { Logger } from "../logger.ts";
import { APP_VERSION } from "../ui/layout.ts";
import { encryptSecret, resolveSharedTokenPlaintext } from "./secret-encryption-service.ts";
import { haTlsCertificate, pinPrimaryHaCertificate } from "./ha-tls-service.ts";
import { fromBase64Url, randomToken, sha256Hex, toBase64Url } from "../utils/crypto.ts";
import { requireSecureHaUrl } from "../ha-url.ts";

const ENROLLMENT_CODE_TTL_MS = 15 * 60 * 1000;
const ENROLLMENT_FETCH_TIMEOUT_MS = 15_000;

export async function loadHaClusterConfigAtBoot(): Promise<void> {
	const row = await repository.haClusterConfigRow();
	if (!row) {
		const sharedToken = config.ha.sharedToken ?? (config.ha.role === "primary" ? randomToken(32) : null);
		await repository.insertHaClusterConfig({
			enabled: config.ha.enabled,
			role: config.ha.role,
			nodeName: config.ha.nodeName,
			primaryUrl: config.ha.primaryUrl,
			primaryAdminUrl: config.ha.primaryAdminUrl,
			sharedTokenEncrypted: sharedToken ? await encryptSecret(sharedToken) : null,
			selfAdminUrl: null,
			clusterEpoch: 0,
		});
		config.ha.sharedToken = sharedToken;
	} else {
		Object.assign(config.ha, {
			enabled: !!row.enabled,
			role: row.role,
			nodeName: row.node_name,
			primaryUrl: row.primary_url,
			primaryAdminUrl: row.primary_admin_url,
			sharedToken: row.shared_token_encrypted ? await resolveSharedTokenPlaintext(row.shared_token_encrypted) : null,
			selfAdminUrl: row.self_admin_url,
			epoch: row.cluster_epoch,

			authorityFence: row.authority_fenced
				? {
						observedEpoch: row.authority_fence_epoch ?? row.cluster_epoch,
						sourceNodeId: row.authority_fence_node_id || "unknown",
						observedAt: row.authority_fenced_at ?? row.updated_at,
					}
				: null,

			quorumFenced: !!row.quorum_fenced,
		});
	}
	validateHaConfig(config.ha);
}

export function deriveMeshUrl(adminUrl: string, meshPort: number): string {
	const url = new URL(requireSecureHaUrl(adminUrl, "HA admin URL"));
	url.protocol = "https:";
	url.port = String(meshPort);
	url.pathname = "/";
	url.search = "";
	return url.origin;
}

interface JoinCode {
	v: 5;
	primaryNodeId: string;
	primaryUrl: string;
	primaryAdminUrl: string;
	primaryCertificate: string;
	enrollmentCode: string;
	primaryEpoch: number;
	primaryVersion: string;
}

function encodeJoinCode(code: JoinCode): string {
	return toBase64Url(new TextEncoder().encode(JSON.stringify(code)));
}

function decodeJoinCode(value: string): JoinCode {
	let parsed: unknown;
	try {
		parsed = JSON.parse(new TextDecoder().decode(fromBase64Url(value.trim())));
	} catch {
		throw new Error("That join code is not valid - check that it was copied in full");
	}
	const code = parsed as Partial<JoinCode>;
	if (
		code.v !== 5 ||
		typeof code.primaryNodeId !== "string" ||
		typeof code.primaryUrl !== "string" ||
		typeof code.primaryAdminUrl !== "string" ||
		typeof code.primaryCertificate !== "string" ||
		!code.primaryCertificate.trim() ||
		typeof code.enrollmentCode !== "string" ||
		!Number.isSafeInteger(code.primaryEpoch) ||
		typeof code.primaryVersion !== "string"
	) {
		throw new Error("That join code is not valid, or was generated by an older version - generate a fresh one and try again");
	}
	return code as JoinCode;
}

export const haEnrollmentClient = {
	async redeem(
		meshUrl: string,
		enrollmentCode: string,
		primaryCertificate: string,
		identity: { nodeId: string; name: string; version: string; adminUrl: string },
	): Promise<string> {
		let response: Response;
		try {
			response = await fetch(`${meshUrl}/_ha/enroll`, {
				method: "POST",
				headers: { authorization: `Bearer ${enrollmentCode}`, "content-type": "application/json" },
				body: JSON.stringify(identity),
				signal: AbortSignal.timeout(ENROLLMENT_FETCH_TIMEOUT_MS),

				tls: { ca: primaryCertificate, checkServerIdentity: () => undefined },
			});
		} catch (error) {
			throw new Error("Could not reach the primary to redeem this join code - check the address and that the primary is running", { cause: error });
		}
		if (!response.ok) {
			throw new Error(
				response.status === 401
					? "This join code has already been used, has expired, or is invalid - generate a fresh one"
					: `The primary rejected the enrollment request (HTTP ${response.status})`,
			);
		}
		const body = (await response.json()) as { sharedToken?: unknown };
		if (typeof body.sharedToken !== "string" || !body.sharedToken) throw new Error("The primary's enrollment response was malformed");
		return body.sharedToken;
	},
};

function applyLive(patch: Partial<HaClusterConfigInsert>, sharedToken: string | undefined): void {
	if (patch.enabled !== undefined) config.ha.enabled = patch.enabled;
	if (patch.role !== undefined) config.ha.role = patch.role;
	if (patch.nodeName !== undefined) config.ha.nodeName = patch.nodeName;
	if (patch.primaryUrl !== undefined) config.ha.primaryUrl = patch.primaryUrl;
	if (patch.primaryAdminUrl !== undefined) config.ha.primaryAdminUrl = patch.primaryAdminUrl;
	if (patch.selfAdminUrl !== undefined) config.ha.selfAdminUrl = patch.selfAdminUrl;
	if (patch.clusterEpoch !== undefined) config.ha.epoch = patch.clusterEpoch;
	if (sharedToken !== undefined) config.ha.sharedToken = sharedToken;
}

function applyLiveAndLogPendingRestart(patch: Partial<HaClusterConfigInsert>, sharedToken: string | undefined, summary: string): void {
	applyLive(patch, sharedToken);
	Logger.warn(`[BurrowGate] HA: ${summary} - restarting to apply`);
}

export async function updateNodeIdentity(input: { nodeName?: string; selfAdminUrl: string }): Promise<void> {
	const selfAdminUrl = requireSecureHaUrl(input.selfAdminUrl, "This node's admin URL");
	const nodeName = input.nodeName?.trim() || config.ha.nodeName;
	const patch: Partial<HaClusterConfigInsert> = { nodeName, selfAdminUrl };
	await repository.updateHaClusterConfig(patch);
	applyLive(patch, undefined);
}

export async function joinCluster(input: { joinCode: string; selfAdminUrl: string; nodeName?: string }): Promise<void> {
	const code = decodeJoinCode(input.joinCode);
	if (code.primaryVersion !== APP_VERSION) {
		throw new Error(
			`This node runs BurrowGate ${APP_VERSION}, but that cluster runs ${code.primaryVersion} - upgrade every node to the same version before joining`,
		);
	}
	const localNodeId = await repository.haNodeId();
	if (code.primaryNodeId === localNodeId) {
		throw new Error("That join code was generated by this same node - a node can't join a cluster to itself");
	}
	if (config.ha.role === "primary") {
		const localNodeId = await repository.haNodeId();
		const otherMembers = (await repository.haClusterMembers()).filter((member) => member.node_id !== localNodeId);
		if (otherMembers.length > 0) {
			throw new Error(
				"This primary still has other registered cluster nodes and cannot join a different cluster. Make those nodes leave or forget them first so the existing cluster is not left without a primary.",
			);
		}
	}
	const selfAdminUrl = requireSecureHaUrl(input.selfAdminUrl, "This node's admin URL");
	const nodeName = input.nodeName?.trim() || config.ha.nodeName;
	const primaryUrl = requireSecureHaUrl(code.primaryUrl, "The join code's primary mesh URL");
	const sharedToken = await haEnrollmentClient.redeem(primaryUrl, code.enrollmentCode, code.primaryCertificate, {
		nodeId: localNodeId,
		name: nodeName,
		version: APP_VERSION,
		adminUrl: selfAdminUrl,
	});

	await pinPrimaryHaCertificate(code.primaryCertificate);

	const patch: HaClusterConfigInsert = {
		enabled: true,
		role: "replica",
		nodeName,
		primaryUrl,
		primaryAdminUrl: requireSecureHaUrl(code.primaryAdminUrl, "The join code's primary admin URL"),
		sharedTokenEncrypted: await encryptSecret(sharedToken),
		selfAdminUrl,

		clusterEpoch: code.primaryEpoch,
	};
	await repository.updateHaClusterConfigAndResetReplicationState(patch);
	config.ha.versionMismatchNodes = [];
	config.ha.authorityFence = null;
	applyLiveAndLogPendingRestart(patch, sharedToken, "joined a cluster as a replica");
}

export async function leaveCluster(): Promise<void> {
	if (config.ha.role !== "replica") throw new Error("This node is not a replica of a cluster - there is nothing to leave");
	const sharedToken = randomToken(32);
	const patch: HaClusterConfigInsert = {
		enabled: true,
		role: "primary",
		nodeName: config.ha.nodeName,
		primaryUrl: null,
		primaryAdminUrl: null,
		sharedTokenEncrypted: await encryptSecret(sharedToken),
		selfAdminUrl: config.ha.selfAdminUrl,

		clusterEpoch: 0,
	};
	await repository.updateHaClusterConfigAndResetMembership(patch);
	config.ha.versionMismatchNodes = [];
	config.ha.authorityFence = null;
	applyLiveAndLogPendingRestart(patch, sharedToken, "left its cluster and became a standalone primary");
}

export async function viewJoinCode(): Promise<string> {
	if (config.ha.role !== "primary") throw new Error("Only the primary can produce a join code");

	const selfAdminUrl = config.ha.selfAdminUrl;
	if (!selfAdminUrl) throw new Error("This node has no admin URL configured - re-run HA setup");
	if (!config.ha.sharedToken) throw new Error("This node has no shared token configured - re-run HA setup");
	const meshUrl = deriveMeshUrl(selfAdminUrl, config.ha.port);
	const { cert: primaryCertificate } = await haTlsCertificate();
	const enrollmentCode = randomToken(32);
	await repository.createHaEnrollmentCode(await sha256Hex(enrollmentCode), Date.now() + ENROLLMENT_CODE_TTL_MS);
	return encodeJoinCode({
		v: 5,
		primaryNodeId: await repository.haNodeId(),
		primaryUrl: meshUrl,
		primaryAdminUrl: selfAdminUrl,
		primaryCertificate,
		enrollmentCode,
		primaryEpoch: config.ha.epoch,
		primaryVersion: APP_VERSION,
	});
}
