import { chmod, mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { config } from "../config.ts";
import { randomToken } from "../utils/crypto.ts";
import { Logger } from "../logger.ts";

export async function readNonEmpty(path: string): Promise<string | null> {
	try {
		const value = (await readFile(path, "utf8")).trim();
		return value || null;
	} catch (error) {
		if ((error as NodeJS.ErrnoException).code === "ENOENT") return null;
		throw error;
	}
}

export async function writePrivateFile(path: string, value: string): Promise<void> {
	await writeFile(path, `${value}\n`, { encoding: "utf8", mode: 0o600 });
	await chmod(path, 0o600);
}

export async function initializeRuntimeSecrets(): Promise<void> {
	await mkdir(config.dataDirectory, { recursive: true, mode: 0o700 });
	await mkdir(config.staticSites.rootDirectory, { recursive: true, mode: 0o700 });

	if (!config.masterKey && !config.masterKeyFile) {
		const path = join(config.dataDirectory, "master.key");
		let value = await readNonEmpty(path);
		if (!value) {
			value = randomToken(48);
			await writePrivateFile(path, value);
			Logger.info(`Generated persistent master key at ${path}`);
		}
		config.masterKeyFile = path;
		config.masterKeyAutoGenerated = true;
	}
}
