import { chmod, rename, rm } from "node:fs/promises";
import { config } from "../config.ts";
import { Logger } from "../logger.ts";
import { fromBase64Url, sha256Bytes, toBase64Url } from "../utils/crypto.ts";

let keyPromise: Promise<CryptoKey> | null = null;

async function masterSecret(): Promise<string> {
	const inline = config.masterKey;
	if (inline) return inline;
	if (config.masterKeyFile) {
		const value = (await Bun.file(config.masterKeyFile).text()).trim();
		if (value) return value;
	}
	throw new Error("TLS private-key storage requires BG_MASTER_KEY or BG_MASTER_KEY_FILE");
}

export async function masterSecretForReplication(): Promise<string> {
	return await masterSecret();
}

export function hasOperatorConfiguredMasterKey(): boolean {
	return !config.masterKeyAutoGenerated;
}

async function atomicWriteFile(path: string, content: string, mode: number): Promise<void> {
	const tempPath = `${path}.tmp-${crypto.randomUUID()}`;
	await Bun.write(tempPath, content);
	await chmod(tempPath, mode);
	await rename(tempPath, path);
}

function pendingMasterKeyFile(): string | null {
	return config.masterKeyFile ? `${config.masterKeyFile}.pending` : null;
}

async function deriveKey(secret: string): Promise<CryptoKey> {
	if (secret.length < 32) throw new Error("BG_MASTER_KEY must contain at least 32 characters");
	return await crypto.subtle.importKey("raw", await sha256Bytes(secret), { name: "AES-GCM" }, false, ["encrypt", "decrypt"]);
}

async function encryptWithKey(value: string, cryptoKey: CryptoKey): Promise<string> {
	const nonce = crypto.getRandomValues(new Uint8Array(12));
	const plaintext = new TextEncoder().encode(value);
	const ciphertext = new Uint8Array(await crypto.subtle.encrypt({ name: "AES-GCM", iv: nonce }, cryptoKey, plaintext));
	return `v1.${toBase64Url(nonce)}.${toBase64Url(ciphertext)}`;
}

async function decryptWithKey(value: string, cryptoKey: CryptoKey): Promise<string> {
	const [version, nonceValue, ciphertextValue] = value.split(".");
	if (version !== "v1" || !nonceValue || !ciphertextValue) throw new Error("Unsupported encrypted secret format");
	const plaintext = await crypto.subtle.decrypt({ name: "AES-GCM", iv: fromBase64Url(nonceValue) }, cryptoKey, fromBase64Url(ciphertextValue));
	return new TextDecoder().decode(plaintext);
}

export async function installMasterKeyFromPrimary(
	key: string,
	encryptDependentSecrets: (encryptWithNewKey: (value: string) => Promise<string>) => Promise<void>,
): Promise<void> {
	if (key.length < 32) throw new Error("The master key received from the primary is too short to be valid");
	if (!config.masterKeyFile) throw new Error("This node has no local master key file to install the primary's key into");
	const pendingPath = pendingMasterKeyFile()!;
	await atomicWriteFile(pendingPath, key, 0o600);
	const newKey = await deriveKey(key);
	await encryptDependentSecrets((value) => encryptWithKey(value, newKey));
	await atomicWriteFile(config.masterKeyFile, key, 0o600);
	await rm(pendingPath, { force: true }).catch(() => undefined);
	resetMasterKeyCache();
}

export async function resolveSharedTokenPlaintext(encrypted: string): Promise<string> {
	try {
		return await decryptSecret(encrypted);
	} catch (error) {
		const pendingPath = pendingMasterKeyFile();
		const pendingKey = pendingPath
			? await Bun.file(pendingPath)
					.text()
					.catch(() => null)
			: null;
		if (!pendingKey?.trim()) throw error;
		const trimmed = pendingKey.trim();
		const plaintext = await decryptWithKey(encrypted, await deriveKey(trimmed));
		Logger.warn("HA: recovered from an interrupted master key promotion, finishing it now");
		await atomicWriteFile(config.masterKeyFile!, trimmed, 0o600);
		await rm(pendingPath!, { force: true }).catch(() => undefined);
		resetMasterKeyCache();
		return plaintext;
	}
}

export function resetMasterKeyCache(): void {
	keyPromise = null;
}

async function encryptionKey(): Promise<CryptoKey> {
	keyPromise ??= masterSecret().then(deriveKey);
	return await keyPromise;
}

export async function encryptSecret(value: string): Promise<string> {
	return await encryptWithKey(value, await encryptionKey());
}

const ENCRYPTED_SECRET_PATTERN = /^v1\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$/u;

export function isEncryptedSecret(value: string): boolean {
	return ENCRYPTED_SECRET_PATTERN.test(value);
}

export async function decryptSecret(value: string): Promise<string> {
	return await decryptWithKey(value, await encryptionKey());
}

export async function assertSecretEncryptionConfigured(): Promise<void> {
	await encryptionKey();
}
