import { afterEach, describe, expect, test } from "bun:test";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { config } from "../src/config.ts";
import { initializeRuntimeSecrets } from "../src/services/runtime-bootstrap-service.ts";

const originalMasterKey = config.masterKey;
const originalMasterKeyFile = config.masterKeyFile;
const originalMasterKeyAutoGenerated = config.masterKeyAutoGenerated;
const originalDataDirectory = config.dataDirectory;
const originalStaticRoot = config.staticSites.rootDirectory;

afterEach(() => {
	config.masterKey = originalMasterKey;
	config.masterKeyFile = originalMasterKeyFile;
	config.masterKeyAutoGenerated = originalMasterKeyAutoGenerated;
	config.dataDirectory = originalDataDirectory;
	config.staticSites.rootDirectory = originalStaticRoot;
});

function currentMasterKeyFile(): string | null {
	return config.masterKeyFile;
}

async function withTempDataDirectory<T>(fn: (tempDir: string) => Promise<T>): Promise<T> {
	const tempDir = await mkdtemp(join(tmpdir(), "bg-runtime-bootstrap-test-"));
	config.dataDirectory = tempDir;
	config.staticSites.rootDirectory = join(tempDir, "static-sites");
	try {
		return await fn(tempDir);
	} finally {
		await rm(tempDir, { recursive: true, force: true });
	}
}

describe("initializeRuntimeSecrets", () => {
	test("generates a persistent key and marks it auto-generated when neither env var is set", async () => {
		await withTempDataDirectory(async (tempDir) => {
			config.masterKey = null;
			config.masterKeyFile = null;
			config.masterKeyAutoGenerated = false;

			await initializeRuntimeSecrets();

			const masterKeyFileAfter = currentMasterKeyFile();
			expect(config.masterKeyAutoGenerated).toBe(true);
			expect(masterKeyFileAfter).toBe(join(tempDir, "master.key"));
			const generated = (await Bun.file(masterKeyFileAfter!).text()).trim();
			expect(generated.length).toBeGreaterThanOrEqual(32);
		});
	});

	test("reuses an already-generated key file across a second call instead of regenerating it", async () => {
		await withTempDataDirectory(async () => {
			config.masterKey = null;
			config.masterKeyFile = null;
			config.masterKeyAutoGenerated = false;

			await initializeRuntimeSecrets();
			const first = (await Bun.file(currentMasterKeyFile()!).text()).trim();

			config.masterKeyFile = null;
			config.masterKeyAutoGenerated = false;
			await initializeRuntimeSecrets();
			const second = (await Bun.file(currentMasterKeyFile()!).text()).trim();

			expect(second).toBe(first);
		});
	});

	test("leaves masterKeyAutoGenerated false when BG_MASTER_KEY is already configured", async () => {
		await withTempDataDirectory(async (tempDir) => {
			config.masterKey = "an-operator-set-key-at-least-32-characters-long";
			config.masterKeyFile = null;
			config.masterKeyAutoGenerated = false;

			await initializeRuntimeSecrets();

			expect(config.masterKeyAutoGenerated).toBe(false);
			expect(config.masterKeyFile).toBeNull();
			expect(await Bun.file(join(tempDir, "master.key")).exists()).toBe(false);
		});
	});

	test("leaves masterKeyAutoGenerated false when BG_MASTER_KEY_FILE is already configured", async () => {
		await withTempDataDirectory(async (tempDir) => {
			config.masterKey = null;
			config.masterKeyFile = "/some/operator-provided/key/file";
			config.masterKeyAutoGenerated = false;

			await initializeRuntimeSecrets();

			expect(config.masterKeyAutoGenerated).toBe(false);
			expect(config.masterKeyFile).toBe("/some/operator-provided/key/file");
			expect(await Bun.file(join(tempDir, "master.key")).exists()).toBe(false);
		});
	});
});
