import { afterAll, afterEach, describe, expect, test } from "bun:test";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { config } from "../src/config.ts";
import {
	decryptSecret,
	encryptSecret,
	hasOperatorConfiguredMasterKey,
	installMasterKeyFromPrimary,
	resetMasterKeyCache,
	resolveSharedTokenPlaintext,
} from "../src/services/secret-encryption-service.ts";

const originalMasterKey = config.masterKey;
const originalMasterKeyFile = config.masterKeyFile;
const originalMasterKeyAutoGenerated = config.masterKeyAutoGenerated;

afterEach(() => {
	config.masterKey = originalMasterKey;
	config.masterKeyFile = originalMasterKeyFile;
	config.masterKeyAutoGenerated = originalMasterKeyAutoGenerated;
});

afterAll(() => {
	resetMasterKeyCache();
});

describe("hasOperatorConfiguredMasterKey", () => {
	test("true when this node's key came from an operator-set env var", () => {
		config.masterKeyAutoGenerated = false;
		expect(hasOperatorConfiguredMasterKey()).toBe(true);
	});

	test("false when this node's key was auto-generated at boot", () => {
		config.masterKeyAutoGenerated = true;
		expect(hasOperatorConfiguredMasterKey()).toBe(false);
	});
});

describe("installMasterKeyFromPrimary", () => {
	test("rejects a key that's too short to be valid", async () => {
		await expect(installMasterKeyFromPrimary("too-short", async () => {})).rejects.toThrow(/too short/);
	});

	test("refuses when this node has no local master key file to write into", async () => {
		config.masterKeyFile = null;
		await expect(installMasterKeyFromPrimary("c".repeat(40), async () => {})).rejects.toThrow(/no local master key file/);
	});

	test("overwrites config.masterKeyFile's contents and takes effect immediately, with no restart", async () => {
		const tempDir = await mkdtemp(join(tmpdir(), "bg-master-key-test-"));
		const keyPath = join(tempDir, "master.key");
		try {
			await writeFile(keyPath, "throwaway-auto-generated-key-at-least-32-chars", { mode: 0o600 });
			config.masterKey = null;
			config.masterKeyFile = keyPath;
			config.masterKeyAutoGenerated = true;
			resetMasterKeyCache();
			const throwawayEncrypted = await encryptSecret("secret-under-throwaway-key");

			const primaryKey = "b".repeat(40);
			await installMasterKeyFromPrimary(primaryKey, async () => {});

			expect((await Bun.file(keyPath).text()).trim()).toBe(primaryKey);
			await expect(decryptSecret(throwawayEncrypted)).rejects.toThrow();

			const encrypted = await encryptSecret("secret-under-real-key");
			expect(await decryptSecret(encrypted)).toBe("secret-under-real-key");
		} finally {
			await rm(tempDir, { recursive: true, force: true });
		}
	});

	test("re-encrypts a dependent secret under the new key before promoting it to master.key", async () => {
		const tempDir = await mkdtemp(join(tmpdir(), "bg-master-key-test-"));
		const keyPath = join(tempDir, "master.key");
		try {
			await writeFile(keyPath, "throwaway-auto-generated-key-at-least-32-chars", { mode: 0o600 });
			config.masterKey = null;
			config.masterKeyFile = keyPath;
			config.masterKeyAutoGenerated = true;
			resetMasterKeyCache();

			const primaryKey = "e".repeat(40);
			let encryptedUnderNewKey = "";
			await installMasterKeyFromPrimary(primaryKey, async (encryptWithNewKey) => {
				encryptedUnderNewKey = await encryptWithNewKey("shared-token-value");
			});

			expect(await decryptSecret(encryptedUnderNewKey)).toBe("shared-token-value");
		} finally {
			await rm(tempDir, { recursive: true, force: true });
		}
	});
});

describe("resolveSharedTokenPlaintext", () => {
	test("finishes an interrupted master key promotion instead of failing to decrypt", async () => {
		const tempDir = await mkdtemp(join(tmpdir(), "bg-master-key-test-"));
		const keyPath = join(tempDir, "master.key");
		const oldKey = "old-key-still-live-at-least-32-characters-long";
		const newKey = "d".repeat(40);
		try {
			await writeFile(keyPath, oldKey, { mode: 0o600 });
			config.masterKey = null;
			config.masterKeyFile = keyPath;
			config.masterKeyAutoGenerated = true;
			resetMasterKeyCache();

			let encryptedUnderNewKey = "";
			await installMasterKeyFromPrimary(newKey, async (encryptWithNewKey) => {
				encryptedUnderNewKey = await encryptWithNewKey("shared-token-value");
			});
			await writeFile(keyPath, oldKey, { mode: 0o600 });
			await writeFile(`${keyPath}.pending`, newKey, { mode: 0o600 });
			resetMasterKeyCache();

			expect(await resolveSharedTokenPlaintext(encryptedUnderNewKey)).toBe("shared-token-value");
			expect((await Bun.file(keyPath).text()).trim()).toBe(newKey);
			expect(await Bun.file(`${keyPath}.pending`).exists()).toBe(false);
		} finally {
			await rm(tempDir, { recursive: true, force: true });
		}
	});
});
