import { page, tablerIcon } from "./layout.ts";

function pagination(id: string): string {
	return `<div class="pagination"><span id="${id}Summary" class="muted">-</span><div class="row"><button id="${id}Previous" class="button secondary compact" type="button">Previous</button><span id="${id}Page" class="page-number">Page 1</span><button id="${id}Next" class="button secondary compact" type="button">Next</button></div></div>`;
}

function sortButton(label: string, key: string): string {
	return `<button class="sort-button" data-sort="${key}" type="button">${label}<span aria-hidden="true"></span></button>`;
}

export function streamsAdminPage(): string {
	return page(
		"Streams",
		`<main class="shell dashboard-shell">
<header class="row between responsive dashboard-header">
  <div><div class="brand"><span class="mark"></span> BurrowGate</div><nav class="dashboard-switch" aria-label="Dashboard"><a href="/_burrowgate/admin">Web Proxy</a><a class="active" href="/_burrowgate/admin/streams">Streams</a></nav><p class="muted header-subtitle">TCP and UDP stream proxy control plane</p></div>
  <div class="dashboard-controls"><label class="site-picker"><span>Stream</span><select id="streamSelector" class="select"><option value="">All streams</option></select></label><label class="site-picker"><span>Date format</span><select id="dateTimeFormat" class="select"><option value="iso-24" selected>YYYY-MM-DD HH:mm:ss</option><option value="dmy-24">DD/MM/YYYY HH:mm:ss</option><option value="mdy-12">MM/DD/YYYY hh:mm:ss AM/PM</option><option value="browser">Browser default</option></select></label><div class="row dashboard-actions"><span id="lastUpdated" class="refresh-status">Loaded on demand</span><button id="refreshDashboard" class="button secondary icon-button" type="button" aria-label="Refresh dashboard" title="Refresh dashboard">${tablerIcon("refresh")}</button><button id="logout" class="button secondary icon-button" type="button" aria-label="Log out" title="Log out">${tablerIcon("logout")}</button></div></div>
</header>

<section class="card date-range-card"><div class="date-range-layout"><div class="date-range-copy"><h2>Date range</h2><p class="muted">Lifecycle logs and transferred-data totals use this interval. Active connections are always live.</p></div><label><span>From</span><input id="dateFrom" class="input" type="datetime-local" step="60"></label><label><span>To</span><input id="dateTo" class="input" type="datetime-local" step="60"></label><div class="row date-range-actions"><button id="applyDateRange" class="button" type="button">Apply</button><button id="resetDateRange" class="button secondary" type="button">Last 24 hours</button></div></div></section>

<section class="grid stats stream-stats">
  <article class="card pad stat"><span class="muted">Active TCP connections</span><strong id="activeTcp">0</strong></article>
  <article class="card pad stat"><span class="muted">Active UDP peers</span><strong id="activeUdp">0</strong></article>
  <article class="card pad stat"><span id="rangeConnectionsLabel" class="muted">Connections (24h)</span><strong id="rangeConnections">0</strong></article>
  <article class="card pad stat"><span id="uniqueIpsLabel" class="muted">Unique IPs (24h)</span><strong id="uniqueIps">0</strong></article>
  <article class="card pad stat"><span id="clientToUpstreamLabel" class="muted">Client to upstream (24h)</span><strong id="clientToUpstream">0 B</strong></article>
  <article class="card pad stat"><span id="upstreamToClientLabel" class="muted">Upstream to client (24h)</span><strong id="upstreamToClient">0 B</strong></article>
  <article class="card pad stat"><span id="rangeErrorsLabel" class="muted">Errors (24h)</span><strong id="rangeErrors">0</strong></article>
</section>

<section class="grid charts-grid">
  <article class="card chart-card"><div class="pad"><h2 id="primaryChartTitle">Stream traffic volume</h2><p id="primaryChartSubtitle" class="muted">Connections, disconnections, and proxy errors</p></div><div class="chart-wrap"><div class="chart-canvas-container"><canvas id="streamTrafficChart"></canvas></div><div id="streamTrafficEmpty" class="empty-state hidden">No stream activity in this range.</div></div></article>
  <article class="card chart-card"><div class="pad"><h2 id="secondaryChartTitle">Stream data volume</h2><p id="secondaryChartSubtitle" class="muted">Payload bytes transferred in both proxy directions</p></div><div class="chart-wrap"><div class="chart-canvas-container"><canvas id="streamBandwidthChart"></canvas></div><div id="streamBandwidthEmpty" class="empty-state hidden">No stream bandwidth in this range.</div></div></article>
</section>

<section class="card geo-card">
  <div class="pad row between responsive"><div><h2>Geographic distribution</h2><p id="geoSubtitle" class="muted">Active connections by country</p></div><select id="geoMetricMode" class="select select-small"><option value="active">Active connections</option><option value="events">Traffic log</option><option value="bandwidth">Bandwidth</option></select></div>
  <div class="geo-layout"><div class="geo-map-wrap"><svg id="geoMap" class="geo-map" role="img" aria-label="World map showing active stream connections by country"></svg><div id="geoTooltip" class="geo-tooltip hidden" role="status"></div><div id="geoMapStatus" class="geo-map-status muted">Loading GeoIP data...</div></div><aside class="geo-sidebar"><div class="row between"><span class="muted">Top countries</span><strong id="geoTotal">0</strong></div><div id="geoCountryList" class="geo-country-list"><p class="muted">No geographic data is available.</p></div><div class="geo-legend"><span>Low</span><div class="geo-legend-scale"><i></i><i></i><i></i><i></i><i></i></div><span>High</span></div><p class="geo-attribution muted">GeoIP data: <a href="https://www.maxmind.com" target="_blank" rel="noreferrer">MaxMind GeoLite2</a><br>Map geometry: <a href="https://github.com/VictorCazanave/svg-maps/tree/master/packages/world" target="_blank" rel="noreferrer">@svg-maps/world / MapSVG</a>, CC BY 4.0</p></aside></div>
</section>

<nav class="tabs" aria-label="Stream dashboard sections"><button class="tab active" data-tab="connections" type="button">Active connections</button><button class="tab" data-tab="events" type="button">Traffic log</button><button class="tab" data-tab="bandwidth" type="button">Bandwidth</button><button class="tab" data-tab="streams" type="button">Streams</button></nav>

<section id="panel-connections" class="tab-panel"><article class="card"><div class="pad section-heading"><div><h2>Live TCP connections and UDP peers</h2><p id="udpPeerNotice" class="muted">UDP peers disconnect after the configured idle timeout.</p></div><button id="refreshConnections" class="button secondary" type="button">Refresh</button></div><div class="table-wrap"><table class="table"><thead><tr><th>${sortButton("Protocol", "protocol")}</th><th>${sortButton("Incoming port", "incomingPort")}</th><th>${sortButton("Client", "clientIp")}</th><th>${sortButton("Country", "countryCode")}</th><th>${sortButton("Connected", "connectedAt")}</th><th>${sortButton("Last activity", "lastActivityAt")}</th><th>${sortButton("To upstream", "clientToUpstreamBytes")}</th><th>${sortButton("To client", "upstreamToClientBytes")}</th></tr></thead><tbody id="activeConnections"><tr><td colspan="8" class="empty-cell">Loading...</td></tr></tbody></table></div></article></section>

<section id="panel-events" class="tab-panel hidden"><article class="card"><div class="pad section-heading"><div><h2>Connection log</h2><p class="muted">TCP socket lifecycle events and synthetic UDP peer sessions.</p></div><button id="refreshEvents" class="button secondary" type="button">Refresh</button></div><div class="toolbar"><label class="search-field"><span>Search</span><input id="eventSearch" class="input" placeholder="IP, connection, reason..."></label><label><span>Protocol</span><select id="eventProtocol" class="select"><option value="">All</option><option value="tcp">TCP</option><option value="udp">UDP</option></select></label><label><span>Event</span><select id="eventType" class="select"><option value="">All</option><option value="connected">Connected</option><option value="disconnected">Disconnected</option><option value="upstream-error">Upstream error</option><option value="listener-error">Listener error</option></select></label><label><span>Country</span><select id="eventCountry" class="select"><option value="">All countries</option></select></label></div><div class="table-wrap"><table class="table"><thead><tr><th>${sortButton("Time", "created_at")}</th><th>${sortButton("Event", "event_type")}</th><th>${sortButton("Protocol", "protocol")}</th><th>${sortButton("Port", "incoming_port")}</th><th>${sortButton("Client", "client_ip")}</th><th>${sortButton("Country", "country_code")}</th><th>${sortButton("Reason", "reason")}</th><th>${sortButton("To upstream", "client_to_upstream_bytes")}</th><th>${sortButton("To client", "upstream_to_client_bytes")}</th></tr></thead><tbody id="streamEvents"><tr><td colspan="9" class="empty-cell">Open the tab to load events.</td></tr></tbody></table></div>${pagination("events")}</article></section>

<section id="panel-bandwidth" class="tab-panel hidden"><article class="card"><div class="pad section-heading"><div><h2>Data proxied per IP and incoming port</h2><p class="muted">Payload bytes are aggregated in one-minute buckets.</p></div><button id="refreshBandwidth" class="button secondary" type="button">Refresh</button></div><div class="toolbar"><label class="search-field"><span>Search</span><input id="bandwidthSearch" class="input" placeholder="IP or country..."></label><label><span>Protocol</span><select id="bandwidthProtocol" class="select"><option value="">All</option><option value="tcp">TCP</option><option value="udp">UDP</option></select></label><label><span>Country</span><select id="bandwidthCountry" class="select"><option value="">All countries</option></select></label></div><div class="table-wrap"><table class="table"><thead><tr><th>${sortButton("Protocol", "protocol")}</th><th>${sortButton("Incoming port", "incoming_port")}</th><th>${sortButton("IP", "ip")}</th><th>${sortButton("Country", "country_code")}</th><th>${sortButton("To upstream", "client_to_upstream_bytes")}</th><th>${sortButton("To client", "upstream_to_client_bytes")}</th><th>${sortButton("Total", "total_bytes")}</th></tr></thead><tbody id="streamBandwidth"><tr><td colspan="7" class="empty-cell">Open the tab to load bandwidth.</td></tr></tbody></table></div>${pagination("bandwidth")}</article></section>

<section id="panel-streams" class="tab-panel hidden"><div class="streams-layout"><article class="card"><div class="pad section-heading"><div><h2>Configured streams</h2><p class="muted">TCP and UDP can share the same numeric incoming port.</p></div><button id="newStream" class="button" type="button">Create</button></div><div id="streamsList" class="sites-list"><div class="empty-state-inline">Loading streams...</div></div></article><article class="card"><div class="pad"><div class="section-heading"><div><h2 id="streamFormTitle">Create stream</h2><p class="muted">Forward raw TCP or UDP traffic to another host.</p></div><button id="cancelStreamEdit" class="button secondary compact hidden" type="button">Cancel edit</button></div><form id="streamForm" class="site-form"><input id="streamId" type="hidden"><div class="site-form-grid"><label><span>Incoming port</span><input id="incomingPort" class="input" type="number" min="1" max="65535" required><small class="muted">Public port BurrowGate listens on for the enabled protocols.</small></label><label><span>Forward host</span><input id="forwardHost" class="input" maxlength="255" placeholder="10.0.0.20" required><small class="muted">Hostname or IP address of the upstream TCP or UDP service.</small></label><label><span>Forward port</span><input id="forwardPort" class="input" type="number" min="1" max="65535" required><small class="muted">Destination port used when connecting to the upstream service.</small></label><label><span>Data retention (days)</span><input id="streamRetentionDays" class="input" type="number" min="1" max="365" required><small class="muted">Applies to connection logs and bandwidth history.</small></label><label><span>TLS certificate</span><select id="streamCertificate" class="select"><option value="">None / TLS passthrough</option></select><small class="muted">Terminates incoming TCP TLS. UDP always remains raw.</small></label></div><div class="row protocol-toggles"><label class="check-row compact-check"><input id="streamTcp" type="checkbox" checked><span><strong>TCP</strong><small class="muted">Proxy connection-oriented TCP traffic.</small></span></label><label class="check-row compact-check"><input id="streamUdp" type="checkbox"><span><strong>UDP</strong><small class="muted">Proxy connectionless UDP datagrams.</small></span></label></div><p id="streamProtocolError" class="badge bad hidden">Enable at least one protocol.</p><p class="notice muted">Docker bridge deployments must publish every incoming port for each selected protocol. The required mapping is shown after saving.</p><pre id="composeMapping" class="compose-mapping hidden"></pre><div class="row site-form-actions"><button id="saveStream" class="button" type="submit">Create</button><button id="resetStreamForm" class="button secondary" type="button">Reset</button></div></form></div></article></div></section>
<div id="toast" class="toast hidden" role="status"></div></main><script src="/_burrowgate/static/chart.umd.js"></script><script type="module" src="/_burrowgate/static/streams-admin.js"></script>`,
	);
}
