import type { JsonSchema } from "./types.ts";

export const streamSchemas: Record<string, JsonSchema> = {
	Stream: {
		type: "object",
		description: "The streamView() shape returned by the repository-backed stream service.",
		required: [
			"id",
			"name",
			"incomingPort",
			"forwardHost",
			"forwardPort",
			"tcpEnabled",
			"udpEnabled",
			"proxyProtocol",
			"certificateId",
			"eventRetentionDays",
			"defaultIpAction",
			"defaultCountryAction",
			"maxConnectionsPerIp",
			"connectionRateLimit",
			"udpAmplificationMaxRatio",
			"originHealthCheck",
			"protection",
			"networkPrivacyPolicy",
			"createdAt",
			"updatedAt",
		],
		properties: {
			id: { type: "string" },
			name: { type: "string", maxLength: 255 },
			incomingPort: { type: "integer", minimum: 1, maximum: 65_535 },
			forwardHost: { type: "string", maxLength: 255, description: "Hostname or IP address, without a scheme, port, or path." },
			forwardPort: { type: "integer", minimum: 1, maximum: 65_535 },
			tcpEnabled: { type: "boolean" },
			udpEnabled: { type: "boolean", description: "At least one of tcpEnabled/udpEnabled is always true." },
			proxyProtocol: { type: "string", enum: ["disabled", "v1", "v2"], description: "v1 is only available when TCP is enabled; use v2 for UDP." },
			certificateId: { type: ["string", "null"], description: "Only set (and only usable) when TCP is enabled." },
			eventRetentionDays: { type: "integer", minimum: 1, maximum: 365 },
			defaultIpAction: { type: "string", enum: ["inherit", "allow", "block"] },
			defaultCountryAction: { type: "string", enum: ["inherit", "allow", "block"] },
			maxConnectionsPerIp: { type: "integer", minimum: 0, maximum: 100_000, description: "0 disables the limit." },
			connectionRateLimit: {
				type: "object",
				required: ["enabled", "algorithm", "windowMs", "max", "refillRate", "refillIntervalMs", "precisionMs"],
				properties: {
					enabled: { type: "boolean" },
					algorithm: { type: "string", enum: ["fixed-window", "sliding-window", "token-bucket"] },
					windowMs: { type: "integer", minimum: 100, maximum: 86_400_000 },
					max: { type: "integer", minimum: 1, maximum: 1_000_000 },
					refillRate: { type: "integer", minimum: 1, maximum: 1_000_000, description: "token-bucket only: tokens added per refill interval." },
					refillIntervalMs: { type: "integer", minimum: 50, maximum: 3_600_000 },
					precisionMs: { type: "integer", minimum: 10, maximum: 60_000, description: "sliding-window only: bucket resolution." },
				},
			},
			udpAmplificationMaxRatio: { type: "integer", minimum: 0, maximum: 10_000, description: "0 disables the guard." },
			originHealthCheck: {
				type: "object",
				required: ["enabled", "intervalSeconds", "timeoutMs", "failureThreshold", "recoveryThreshold"],
				properties: {
					enabled: { type: "boolean" },
					intervalSeconds: { type: "integer", minimum: 3, maximum: 3600 },
					timeoutMs: { type: "integer", minimum: 250, maximum: 60_000 },
					failureThreshold: { type: "integer", minimum: 1, maximum: 20 },
					recoveryThreshold: { type: "integer", minimum: 1, maximum: 20 },
				},
			},
			protection: { $ref: "#/components/schemas/StreamProtectionPolicy" },
			networkPrivacyPolicy: { $ref: "#/components/schemas/NetworkPrivacyPolicy" },
			createdAt: { type: "integer", description: "Unix milliseconds." },
			updatedAt: { type: "integer", description: "Unix milliseconds." },
		},
	},
	StreamInput: {
		type: "object",
		description:
			"All fields are optional on update (existing values are kept); name, incomingPort, forwardHost, forwardPort are required on create. At least one of tcpEnabled/udpEnabled must end up true. `effectiveAt` is only meaningful on update - see PUT /streams/{id}.",
		properties: {
			name: { type: "string", maxLength: 255 },
			incomingPort: {
				type: "integer",
				minimum: 1,
				maximum: 65_535,
				description: "Must not collide with BurrowGate's own HTTP/HTTPS listener port, or another stream's port+protocol.",
			},
			forwardHost: { type: "string", maxLength: 255 },
			forwardPort: { type: "integer", minimum: 1, maximum: 65_535 },
			tcpEnabled: { type: "boolean", default: true },
			udpEnabled: { type: "boolean", default: false },
			proxyProtocol: { type: "string", enum: ["disabled", "v1", "v2"], default: "disabled" },
			certificateId: {
				type: ["string", "null"],
				description: "Must reference an active, unexpired certificate with usable TLS material. Requires tcpEnabled.",
			},
			eventRetentionDays: { type: "integer", minimum: 1, maximum: 365 },
			maxConnectionsPerIp: { type: "integer", minimum: 0, maximum: 100_000, default: 0 },
			connectionRateLimitEnabled: { type: "boolean", default: false },
			connectionRateLimitAlgorithm: { type: "string", enum: ["fixed-window", "sliding-window", "token-bucket"], default: "sliding-window" },
			connectionRateLimitWindowMs: { type: "integer", minimum: 100, maximum: 86_400_000, default: 60_000 },
			connectionRateLimitMax: { type: "integer", minimum: 1, maximum: 1_000_000, default: 60 },
			connectionRateLimitRefillRate: { type: "integer", minimum: 1, maximum: 1_000_000, default: 10 },
			connectionRateLimitRefillIntervalMs: { type: "integer", minimum: 50, maximum: 3_600_000, default: 1000 },
			connectionRateLimitPrecisionMs: { type: "integer", minimum: 10, maximum: 60_000, default: 100 },
			udpAmplificationMaxRatio: { type: "integer", minimum: 0, maximum: 10_000, default: 0 },
			originHealthCheckEnabled: { type: "boolean", default: false },
			originHealthCheckIntervalSeconds: { type: "integer", minimum: 3, maximum: 3600, default: 10 },
			originHealthCheckTimeoutMs: { type: "integer", minimum: 250, maximum: 60_000, default: 3000 },
			originHealthCheckFailureThreshold: { type: "integer", minimum: 1, maximum: 20, default: 3 },
			originHealthCheckRecoveryThreshold: { type: "integer", minimum: 1, maximum: 20, default: 2 },
			effectiveAt: {
				type: "integer",
				description:
					"Unix milliseconds. Only consulted on update, and only when the change would force a listener restart (port/host/protocol toggle/certificate/PROXY-protocol changes). If set, that restart-requiring part of the change is scheduled instead of applied immediately - see `pendingChange` in the response.",
			},
		},
	},
	StreamRuntimeStatus: {
		type: "object",
		description: "Live TCP/UDP listener status for one stream, from StreamProxyManager.statusesView().",
		required: ["id", "tcp", "udp", "error", "activeTcpConnections", "activeUdpPeers"],
		properties: {
			id: { type: "string" },
			tcp: { type: "string", enum: ["disabled", "active", "error"] },
			udp: { type: "string", enum: ["disabled", "active", "error"] },
			error: { type: ["string", "null"] },
			activeTcpConnections: { type: "integer" },
			activeUdpPeers: { type: "integer" },
		},
	},
	StreamActiveConnection: {
		type: "object",
		description: "One live TCP connection or UDP peer, from StreamProxyManager.activeConnections().",
		required: [
			"id",
			"streamId",
			"incomingPort",
			"protocol",
			"clientIp",
			"clientPort",
			"countryCode",
			"asn",
			"asnOrg",
			"networkPrivacy",
			"connectedAt",
			"lastActivityAt",
			"clientToUpstreamBytes",
			"upstreamToClientBytes",
			"username",
		],
		properties: {
			id: { type: "string" },
			streamId: { type: "string" },
			incomingPort: { type: "integer" },
			protocol: { type: "string", enum: ["tcp", "udp"] },
			clientIp: { type: "string" },
			clientPort: { type: "integer" },
			countryCode: { type: ["string", "null"] },
			asn: { type: ["integer", "null"] },
			asnOrg: { type: ["string", "null"] },
			networkPrivacy: { type: "array", items: { type: "string" }, description: "Matched network-privacy category IDs (e.g. tor, hosting)." },
			connectedAt: { type: "integer", description: "Unix milliseconds." },
			lastActivityAt: { type: "integer", description: "Unix milliseconds." },
			clientToUpstreamBytes: { type: "integer" },
			upstreamToClientBytes: { type: "integer" },
			username: { type: ["string", "null"], description: "The admin user who initiated this connection via a manual test, if applicable; null otherwise." },
		},
	},
	StreamCertificateOption: {
		type: "object",
		description: "A certificate available to assign to a stream's TLS listener (certificateView() in stream-admin-routes.ts).",
		required: ["id", "primaryDomain", "alternativeNames", "expiresAt", "siteName", "publicHost"],
		properties: {
			id: { type: "string" },
			primaryDomain: { type: "string" },
			alternativeNames: { type: "array", items: { type: "string" } },
			expiresAt: { type: "integer", description: "Unix milliseconds." },
			siteName: { type: "string", description: "Name of the site this certificate belongs to." },
			publicHost: { type: "string", description: "Public hostname of the site this certificate belongs to." },
		},
	},

	StreamProtectionPolicy: {
		type: "object",
		description: "Resolved by resolveStreamProtectionPolicy(); this is both the Stream.protection field and the GET/PUT .../streams/protection-policy body.",
		required: ["mode", "rulesetIds", "excludedRuleIds", "banDurations"],
		properties: {
			mode: { type: "string", enum: ["disabled", "monitor", "block"] },
			rulesetIds: {
				type: "array",
				maxItems: 32,
				items: { type: "string", pattern: "^[a-z0-9][a-z0-9._-]{0,127}$" },
				description: "Enabled ruleset IDs - see GET .../streams/protection-catalog for the full catalog.",
			},
			excludedRuleIds: { type: "array", maxItems: 256, items: { type: "string", pattern: "^[A-Z0-9][A-Z0-9._:-]{0,127}$" } },
			banDurations: { $ref: "#/components/schemas/SiteBanDurationsPolicy" },
		},
	},
	StreamProtectionPolicyInput: {
		type: "object",
		description:
			"Partial update; omitted fields (including omitted banDurations sub-fields) keep their current value. Passing the whole body as null resets to defaults.",
		properties: {
			mode: { type: "string", enum: ["disabled", "monitor", "block"] },
			rulesetIds: { type: "array", maxItems: 32, items: { type: "string" } },
			excludedRuleIds: {
				oneOf: [{ type: "null" }, { type: "string", description: "Comma/whitespace-separated rule IDs." }, { type: "array", items: { type: "string" } }],
				description: "null or an empty string clears the list.",
			},
			banDurations: { $ref: "#/components/schemas/SiteBanDurationsPolicy" },
		},
	},
	StreamRuleSetCatalogEntry: {
		type: "object",
		description: "One available stream protection ruleset, from streamRuleSetCatalog() (src/services/stream-protection-service.ts).",
		required: ["id", "title", "version", "description", "protocol", "decode"],
		properties: {
			id: { type: "string" },
			title: { type: "string" },
			version: { type: "string" },
			description: { type: "string" },
			protocol: {
				type: "string",
				description: 'Which decoder populates this ruleset\'s fields: "generic" (connection metadata only) or an application protocol id.',
			},
			decode: {
				type: "object",
				required: ["timeoutMs", "maxBytes"],
				properties: { timeoutMs: { type: "integer" }, maxBytes: { type: "integer" } },
			},
		},
	},

	StreamBandwidthPolicy: {
		type: "object",
		description:
			"Per-protocol bandwidth-limit auto-ban policy for a stream. This is NOT embedded in the Stream response; it's only exposed via GET/PUT .../streams/bandwidth-limit-policy.",
		required: ["tcp", "udp"],
		properties: {
			tcp: { $ref: "#/components/schemas/SiteBandwidthLimitPolicy" },
			udp: { $ref: "#/components/schemas/SiteBandwidthLimitPolicy" },
		},
	},
	StreamBandwidthPolicyInput: {
		type: "object",
		description: "Partial update; omitted fields (including omitted tcp/udp sub-fields) keep their current value.",
		properties: {
			tcp: { $ref: "#/components/schemas/SiteBandwidthLimitPolicy" },
			udp: { $ref: "#/components/schemas/SiteBandwidthLimitPolicy" },
		},
	},

	StreamNotificationEventTypeMap: {
		type: "object",
		description:
			"Whether each event type triggers an outbound notification for this stream. Unlike NotificationEventTypeMap (sites), streams only support this subset of event types.",
		properties: Object.fromEntries(
			[
				"origin_unhealthy",
				"origin_recovered",
				"pool_unhealthy",
				"pool_recovered",
				"internet_down",
				"internet_up",
				"ip_banned",
				"stream_origin_unhealthy",
				"stream_origin_recovered",
				"stream_ip_banned",
			].map((key) => [key, { type: "boolean" }]),
		),
	},
	StreamNotificationPolicy: {
		type: "object",
		description:
			"The GET/PUT .../streams/notification-policy response shape. Reshaped by the route handler from the stored policy: webhookUrl/webhookSecret are never returned, only whether one is configured.",
		required: ["enabled", "provider", "webhookConfigured", "eventTypes"],
		properties: {
			enabled: { type: "boolean" },
			provider: { type: "string", enum: ["generic", "slack", "discord", "ntfy"] },
			webhookConfigured: { type: "boolean" },
			eventTypes: { $ref: "#/components/schemas/StreamNotificationEventTypeMap" },
		},
	},
	StreamNotificationPolicyInput: {
		type: "object",
		description: "Partial update; omitted fields keep their current value.",
		properties: {
			enabled: { type: "boolean" },
			provider: { type: "string", enum: ["generic", "slack", "discord", "ntfy"] },
			webhookUrl: {
				type: "string",
				maxLength: 4096,
				description: "Absolute http(s) URL without embedded credentials. Required (on this or a prior update) when enabled is true.",
			},
			webhookSecret: { type: "string", maxLength: 4096, description: "Used to sign outbound webhook payloads." },
			clearWebhook: {
				type: "boolean",
				default: false,
				description: "If true, removes the stored webhook URL and secret instead of keeping or replacing them.",
			},
			eventTypes: { $ref: "#/components/schemas/StreamNotificationEventTypeMap" },
		},
	},
	StreamNotificationRecord: {
		type: "object",
		description: "One entry in a stream's notification outbox, reshaped (camelCase) by the route handler for GET .../streams/notifications.",
		required: ["id", "type", "severity", "summary", "status", "attempts", "lastError", "occurredAt", "createdAt", "deliveredAt"],
		properties: {
			id: { type: "string" },
			type: {
				type: "string",
				enum: [
					"origin_unhealthy",
					"origin_recovered",
					"pool_unhealthy",
					"pool_recovered",
					"internet_down",
					"internet_up",
					"ip_banned",
					"stream_origin_unhealthy",
					"stream_origin_recovered",
					"stream_ip_banned",
				],
			},
			severity: { type: "string", enum: ["info", "warning", "critical"] },
			summary: { type: "string" },
			status: { type: "string", enum: ["pending", "delivered", "failed"] },
			attempts: { type: "integer" },
			lastError: { type: ["string", "null"] },
			occurredAt: { type: "integer", description: "Unix milliseconds." },
			createdAt: { type: "integer", description: "Unix milliseconds." },
			deliveredAt: { type: ["integer", "null"], description: "Unix milliseconds, or null if not yet delivered." },
		},
	},

	StreamIpRuleRecord: {
		type: "object",
		description: "Returned as-is from the repository (snake_case field names) by both the paged listing and the create endpoint.",
		required: ["id", "stream_id", "network_cidr", "action", "reason", "created_at", "expires_at"],
		properties: {
			id: { type: "string" },
			stream_id: { type: "string" },
			network_cidr: { type: "string", description: "A single IP address or CIDR range." },
			action: { type: "string", enum: ["allow", "block"] },
			reason: { type: "string" },
			created_at: { type: "integer", description: "Unix milliseconds." },
			expires_at: { type: ["integer", "null"], description: "Unix milliseconds, or null if the rule never expires." },
		},
	},
	StreamCountryRuleRecord: {
		type: "object",
		description: "Returned as-is from the repository (snake_case field names) by both GET .../streams/network-policy and the create endpoint.",
		required: ["id", "stream_id", "country_code", "action", "reason", "created_at", "expires_at"],
		properties: {
			id: { type: "string" },
			stream_id: { type: "string" },
			country_code: { type: "string", minLength: 2, maxLength: 2 },
			action: { type: "string", enum: ["allow", "block"] },
			reason: { type: "string" },
			created_at: { type: "integer" },
			expires_at: { type: ["integer", "null"] },
		},
	},
	StreamAsnRuleRecord: {
		type: "object",
		description: "Returned as-is from the repository (snake_case field names) by both GET .../streams/network-policy and the create endpoint.",
		required: ["id", "stream_id", "asn", "action", "reason", "created_at", "expires_at"],
		properties: {
			id: { type: "string" },
			stream_id: { type: "string" },
			asn: { type: "integer", minimum: 1 },
			action: { type: "string", enum: ["allow", "block"] },
			reason: { type: "string" },
			created_at: { type: "integer" },
			expires_at: { type: ["integer", "null"] },
		},
	},

	StreamEventRecord: {
		type: "object",
		description:
			"One row from the stream_events table, as returned (snake_case) by GET .../streams/events. network_privacy is added by the route handler alongside the raw network_privacy_json.",
		required: [
			"id",
			"stream_id",
			"incoming_port",
			"connection_id",
			"protocol",
			"event_type",
			"client_ip",
			"client_port",
			"country_code",
			"asn",
			"asn_org",
			"network_privacy_json",
			"network_privacy",
			"reason",
			"error",
			"protection_rule_id",
			"client_to_upstream_bytes",
			"upstream_to_client_bytes",
			"duration_ms",
			"username",
			"created_at",
		],
		properties: {
			id: { type: "string" },
			stream_id: { type: "string" },
			incoming_port: { type: "integer" },
			connection_id: { type: ["string", "null"] },
			protocol: { type: "string", enum: ["tcp", "udp"] },
			event_type: { type: "string", enum: ["connected", "disconnected", "upstream-error", "listener-error", "blocked", "throttled", "monitored"] },
			client_ip: { type: ["string", "null"] },
			client_port: { type: ["integer", "null"] },
			country_code: { type: ["string", "null"] },
			asn: { type: ["integer", "null"] },
			asn_org: { type: ["string", "null"] },
			network_privacy_json: {
				type: ["string", "null"],
				description: "Raw JSON array of matched network-privacy category IDs - see network_privacy for the parsed form.",
			},
			network_privacy: { type: "array", items: { type: "string" } },
			reason: { type: ["string", "null"] },
			error: { type: ["string", "null"] },
			protection_rule_id: { type: ["string", "null"] },
			client_to_upstream_bytes: { type: "integer" },
			upstream_to_client_bytes: { type: "integer" },
			duration_ms: { type: ["integer", "null"], description: "Only known once the connection has closed." },
			username: { type: ["string", "null"], description: "The admin user who initiated this connection via a manual test, if applicable; null otherwise." },
			created_at: { type: "integer", description: "Unix milliseconds." },
		},
	},
	StreamBandwidthRow: {
		type: "object",
		description: "One aggregated per-IP bandwidth row from the stream_bandwidth_minutes table, as returned (snake_case) by GET .../streams/bandwidth.",
		required: ["stream_id", "incoming_port", "ip", "country_code", "protocol", "client_to_upstream_bytes", "upstream_to_client_bytes", "total_bytes"],
		properties: {
			stream_id: { type: "string" },
			incoming_port: { type: ["integer", "string"], description: "Numeric; may arrive as a numeric string depending on the DB driver's aggregation result." },
			ip: { type: "string" },
			country_code: { type: "string" },
			protocol: { type: "string", enum: ["tcp", "udp"] },
			client_to_upstream_bytes: { type: ["integer", "string"] },
			upstream_to_client_bytes: { type: ["integer", "string"] },
			total_bytes: { type: ["integer", "string"] },
		},
	},

	NetworkPrivacyCategoryMeta: {
		type: "object",
		description: "One entry in the network-privacy category catalog (e.g. tor, a hosting-provider ASN category).",
		required: ["id", "label", "description"],
		properties: {
			id: { type: "string" },
			label: { type: "string" },
			description: { type: "string" },
		},
	},
	GeoIpDatabaseStatus: {
		type: "object",
		required: ["enabled", "available", "databasePath", "databaseModifiedAt", "error"],
		properties: {
			enabled: { type: "boolean" },
			available: { type: "boolean" },
			databasePath: { type: "string" },
			databaseModifiedAt: { type: ["integer", "null"], description: "Unix milliseconds." },
			error: { type: ["string", "null"] },
		},
	},
	GeoIpStatus: {
		allOf: [{ $ref: "#/components/schemas/GeoIpDatabaseStatus" }],
		type: "object",
		description: "Status of the country-lookup GeoIP database, plus a nested status for the separate ASN-lookup database.",
		required: ["asn"],
		properties: {
			asn: { $ref: "#/components/schemas/GeoIpDatabaseStatus" },
		},
	},
};
