import type { JsonSchema } from "./types.ts";

export const schemas: Record<string, JsonSchema> = {
	ErrorResponse: {
		type: "object",
		required: ["error"],
		properties: { error: { type: "string", description: "Human-readable error message. Not a fixed enum - treat as free text for display." } },
	},
	OAuthErrorResponse: {
		type: "object",
		description: "Used only by the OIDC back-channel-logout endpoint, per RFC 6749.",
		required: ["error"],
		properties: {
			error: { type: "string", const: "invalid_request" },
			error_description: { type: "string" },
		},
	},

	ApiToken: {
		type: "object",
		description: "An API token owned by the caller. The plaintext secret is included only in the creation response, never again.",
		required: ["id", "name", "prefix", "scope", "createdAt", "expiresAt"],
		properties: {
			id: { type: "string" },
			name: { type: "string", maxLength: 100 },
			prefix: { type: "string", description: "First 13 characters of the token, for display (e.g. `bgat_Ab3fG9zK`)." },
			scope: { type: "string", enum: ["monitoring", "full"] },
			createdAt: { type: "integer", description: "Unix milliseconds." },
			expiresAt: { type: ["integer", "null"], description: "Unix milliseconds, or null if the token never expires." },
		},
	},
	ApiTokenCreated: {
		allOf: [{ $ref: "#/components/schemas/ApiToken" }],
		type: "object",
		description: "Returned once, at creation time, with the plaintext secret. It is never shown or retrievable again.",
		required: ["token"],
		properties: {
			token: { type: "string", description: "The plaintext bearer token. Prefixed `bgro_` for a monitoring-scope token, `bgat_` for full-access." },
		},
	},
	ApiTokenInput: {
		type: "object",
		required: ["name", "scope"],
		properties: {
			name: { type: "string", minLength: 1, maxLength: 100 },
			scope: {
				type: "string",
				enum: ["monitoring", "full"],
				description: "`monitoring` may only be created by an administrator. `full` may be created by any enabled user, for themself.",
			},
			expiresInDays: {
				type: ["integer", "null"],
				minimum: 1,
				maximum: 365,
				default: 90,
				description: "Days until expiry, or null for no expiry.",
			},
		},
	},

	PendingChange: {
		type: ["object", "null"],
		description: "Present only when an update deferred a change that requires a listener restart (an `effectiveAt` was supplied). Null otherwise.",
		properties: {
			id: { type: "string" },
			entityType: { type: "string", enum: ["site", "stream"] },
			entityId: { type: "string" },
			changes: { type: "object", additionalProperties: true },
			summary: { type: "string" },
			applyAt: { type: "integer", description: "Unix milliseconds." },
			status: { type: "string", enum: ["pending", "applied", "failed"] },
			attempts: { type: "integer" },
			lastError: { type: ["string", "null"] },
			createdBy: { type: ["string", "null"] },
			createdAt: { type: "integer" },
			appliedAt: { type: ["integer", "null"] },
		},
	},

	ChallengePolicyStep: {
		type: "object",
		description:
			"One step of a site's or route's challenge chain. `config` is provider-specific; known providers are pow-sha256, hcaptcha, turnstile, recaptcha-v2, recaptcha-v3, snake, slider, trace, password, and quiz - see docs/ADDING_CHALLENGES.md.",
		required: ["provider", "config"],
		properties: {
			provider: { type: "string", maxLength: 128 },
			config: { type: "object", additionalProperties: true },
		},
	},

	HeaderAssignment: {
		type: "object",
		required: ["name", "value"],
		properties: {
			name: { type: "string", maxLength: 128, description: "Lower-cased HTTP header name. Connection/proxy-framing headers cannot be set." },
			value: { type: "string", maxLength: 8192 },
		},
	},
	HeaderMutationPolicy: {
		type: "object",
		required: ["set", "remove"],
		properties: {
			set: { type: "array", maxItems: 64, items: { $ref: "#/components/schemas/HeaderAssignment" } },
			remove: { type: "array", maxItems: 64, items: { type: "string" } },
		},
	},
	RequestLimits: {
		type: "object",
		description: "0 means unlimited for each field.",
		required: ["maxBodyBytes", "maxRequestTargetBytes", "maxHeaderBytes"],
		properties: {
			maxBodyBytes: { type: "integer", minimum: 0, maximum: 1_099_511_627_776 },
			maxRequestTargetBytes: { type: "integer", minimum: 0, maximum: 1_048_576 },
			maxHeaderBytes: { type: "integer", minimum: 0, maximum: 1_048_576 },
		},
	},
	RouteRequestLimits: {
		type: "object",
		description: "null inherits the site's limit for that field.",
		required: ["maxBodyBytes", "maxRequestTargetBytes", "maxHeaderBytes"],
		properties: {
			maxBodyBytes: { type: ["integer", "null"], minimum: 0, maximum: 1_099_511_627_776 },
			maxRequestTargetBytes: { type: ["integer", "null"], minimum: 0, maximum: 1_048_576 },
			maxHeaderBytes: { type: ["integer", "null"], minimum: 0, maximum: 1_048_576 },
		},
	},
	SiteStaticCachePolicy: {
		type: "object",
		required: ["mode", "ttlSeconds", "maxObjectBytes", "extensions"],
		properties: {
			mode: { type: "string", enum: ["disabled", "enabled"] },
			ttlSeconds: { type: "integer", minimum: 1, maximum: 604_800 },
			maxObjectBytes: { type: "integer", minimum: 1024, description: "Ceiling is the instance's configured static-cache object size limit." },
			extensions: { type: "array", minItems: 1, maxItems: 64, items: { type: "string", pattern: "^\\.[a-z0-9][a-z0-9._-]*$" } },
		},
	},
	RouteStaticCachePolicy: {
		type: "object",
		description: "Any field left null inherits the site's value.",
		required: ["mode", "ttlSeconds", "maxObjectBytes", "extensions"],
		properties: {
			mode: { type: "string", enum: ["inherit", "disabled", "enabled"] },
			ttlSeconds: { type: ["integer", "null"], minimum: 1, maximum: 604_800 },
			maxObjectBytes: { type: ["integer", "null"], minimum: 1024 },
			extensions: { type: ["array", "null"], items: { type: "string" } },
		},
	},
	SiteManagedProtectionPolicy: {
		type: "object",
		required: ["mode", "rulesetId", "excludedRuleIds"],
		properties: {
			mode: { type: "string", enum: ["disabled", "monitor", "block"] },
			rulesetId: { type: "string", pattern: "^[a-z0-9][a-z0-9._-]{0,127}$" },
			excludedRuleIds: { type: "array", maxItems: 256, items: { type: "string" } },
		},
	},
	RouteManagedProtectionPolicy: {
		type: "object",
		required: ["mode", "excludedRuleIds"],
		properties: {
			mode: { type: "string", enum: ["inherit", "disabled", "monitor", "block"] },
			excludedRuleIds: { type: "array", maxItems: 256, items: { type: "string" } },
		},
	},
	SiteBanDurationsPolicy: {
		type: "object",
		description: "Seconds to ban an IP for a violation of each severity. 0 disables banning for that severity.",
		required: ["low", "medium", "high", "critical"],
		properties: {
			low: { type: "integer", minimum: 0, maximum: 2_592_000 },
			medium: { type: "integer", minimum: 0, maximum: 2_592_000 },
			high: { type: "integer", minimum: 0, maximum: 2_592_000 },
			critical: { type: "integer", minimum: 0, maximum: 2_592_000 },
		},
	},
	RouteBanDurationsPolicy: {
		type: "object",
		description: "Any field left null inherits the site's value for that severity.",
		required: ["low", "medium", "high", "critical"],
		properties: {
			low: { type: ["integer", "null"], minimum: 0, maximum: 2_592_000 },
			medium: { type: ["integer", "null"], minimum: 0, maximum: 2_592_000 },
			high: { type: ["integer", "null"], minimum: 0, maximum: 2_592_000 },
			critical: { type: ["integer", "null"], minimum: 0, maximum: 2_592_000 },
		},
	},
	SiteBandwidthLimitPolicy: {
		type: "object",
		required: ["enabled", "maxBytes", "windowSeconds", "banSeconds"],
		properties: {
			enabled: { type: "boolean" },
			maxBytes: { type: "integer", minimum: 1, maximum: 1_099_511_627_776 },
			windowSeconds: { type: "integer", minimum: 1, maximum: 3600 },
			banSeconds: { type: "integer", minimum: 0, maximum: 2_592_000 },
		},
	},
	RouteBandwidthLimitPolicy: {
		type: "object",
		description: "Any field left null inherits the site's value.",
		required: ["enabled", "maxBytes", "windowSeconds", "banSeconds"],
		properties: {
			enabled: { type: ["boolean", "null"] },
			maxBytes: { type: ["integer", "null"], minimum: 1, maximum: 1_099_511_627_776 },
			windowSeconds: { type: ["integer", "null"], minimum: 1, maximum: 3600 },
			banSeconds: { type: ["integer", "null"], minimum: 0, maximum: 2_592_000 },
		},
	},
	SiteBodyCapturePolicy: {
		type: "object",
		required: ["mode", "maxRequestBytes", "maxResponseBytes", "expiresAt", "contentTypes"],
		properties: {
			mode: { type: "string", enum: ["disabled", "enabled"] },
			maxRequestBytes: { type: "integer", minimum: 0 },
			maxResponseBytes: { type: "integer", minimum: 0 },
			expiresAt: { type: ["integer", "null"], description: "Unix milliseconds after which capture automatically stops, or null for no expiry." },
			contentTypes: { type: "array", maxItems: 32, items: { type: "string" }, description: "Text-based MIME types only, or `*` for all text types." },
		},
	},
	RouteBodyCapturePolicy: {
		type: "object",
		description: "Any field left null inherits the site's value.",
		required: ["mode", "maxRequestBytes", "maxResponseBytes", "expiresAt", "contentTypes"],
		properties: {
			mode: { type: "string", enum: ["inherit", "disabled", "enabled"] },
			maxRequestBytes: { type: ["integer", "null"], minimum: 0 },
			maxResponseBytes: { type: ["integer", "null"], minimum: 0 },
			expiresAt: { type: ["integer", "null"] },
			contentTypes: { type: ["array", "null"], items: { type: "string" } },
		},
	},
	SiteHeaderCapturePolicy: {
		type: "object",
		required: ["mode", "redactAuthHeaders", "redactedHeaders", "expiresAt"],
		properties: {
			mode: { type: "string", enum: ["disabled", "enabled"] },
			redactAuthHeaders: { type: "boolean" },
			redactedHeaders: { type: "array", maxItems: 32, items: { type: "string" } },
			expiresAt: { type: ["integer", "null"] },
		},
	},
	RouteHeaderCapturePolicy: {
		type: "object",
		description: "Any field left null inherits the site's value.",
		required: ["mode", "redactAuthHeaders", "redactedHeaders", "expiresAt"],
		properties: {
			mode: { type: "string", enum: ["inherit", "disabled", "enabled"] },
			redactAuthHeaders: { type: ["boolean", "null"] },
			redactedHeaders: { type: ["array", "null"], items: { type: "string" } },
			expiresAt: { type: ["integer", "null"] },
		},
	},
	SiteCorsPolicy: {
		type: "object",
		required: ["mode", "allowedOrigins", "allowedMethods", "allowedHeaders", "exposedHeaders", "allowCredentials", "maxAgeSeconds"],
		properties: {
			mode: { type: "string", enum: ["disabled", "enabled"] },
			allowedOrigins: {
				type: "array",
				maxItems: 64,
				items: { type: "string" },
				description: "Each entry `*` or an exact `scheme://host[:port]`. `*` cannot be combined with allowCredentials.",
			},
			allowedMethods: { type: "array", maxItems: 32, items: { type: "string" } },
			allowedHeaders: { type: "array", maxItems: 64, items: { type: "string" } },
			exposedHeaders: { type: "array", maxItems: 64, items: { type: "string" }, description: "Cannot include headers BurrowGate itself manages." },
			allowCredentials: { type: "boolean" },
			maxAgeSeconds: { type: "integer", minimum: 0, maximum: 86_400 },
		},
	},
	RouteCorsPolicy: {
		type: "object",
		description: "Any field left null inherits the site's value.",
		required: ["mode", "allowedOrigins", "allowedMethods", "allowedHeaders", "exposedHeaders", "allowCredentials", "maxAgeSeconds"],
		properties: {
			mode: { type: "string", enum: ["inherit", "disabled", "enabled"] },
			allowedOrigins: { type: ["array", "null"], items: { type: "string" } },
			allowedMethods: { type: ["array", "null"], items: { type: "string" } },
			allowedHeaders: { type: ["array", "null"], items: { type: "string" } },
			exposedHeaders: { type: ["array", "null"], items: { type: "string" } },
			allowCredentials: { type: ["boolean", "null"] },
			maxAgeSeconds: { type: ["integer", "null"], minimum: 0, maximum: 86_400 },
		},
	},
	SiteHstsPolicy: {
		type: "object",
		description: "preload requires includeSubDomains and a maxAgeSeconds of at least 31536000 (1 year).",
		required: ["mode", "maxAgeSeconds", "includeSubDomains", "preload"],
		properties: {
			mode: { type: "string", enum: ["disabled", "enabled"] },
			maxAgeSeconds: { type: "integer", minimum: 0, maximum: 63_072_000 },
			includeSubDomains: { type: "boolean" },
			preload: { type: "boolean" },
		},
	},
	SiteHttpPolicy: {
		type: "object",
		required: [
			"requestHeaders",
			"responseHeaders",
			"limits",
			"cache",
			"protection",
			"banDurations",
			"bandwidthLimit",
			"bodyCapture",
			"headerCapture",
			"cors",
			"hsts",
		],
		properties: {
			requestHeaders: { $ref: "#/components/schemas/HeaderMutationPolicy" },
			responseHeaders: { $ref: "#/components/schemas/HeaderMutationPolicy" },
			limits: { $ref: "#/components/schemas/RequestLimits" },
			cache: { $ref: "#/components/schemas/SiteStaticCachePolicy" },
			protection: { $ref: "#/components/schemas/SiteManagedProtectionPolicy" },
			banDurations: { $ref: "#/components/schemas/SiteBanDurationsPolicy" },
			bandwidthLimit: { $ref: "#/components/schemas/SiteBandwidthLimitPolicy" },
			bodyCapture: { $ref: "#/components/schemas/SiteBodyCapturePolicy" },
			headerCapture: { $ref: "#/components/schemas/SiteHeaderCapturePolicy" },
			cors: { $ref: "#/components/schemas/SiteCorsPolicy" },
			hsts: { $ref: "#/components/schemas/SiteHstsPolicy" },
		},
	},
	RouteHttpPolicy: {
		type: "object",
		description: "Every sub-policy's fields default to inherit/null, meaning \"use the site's value\", unless explicitly overridden.",
		required: ["requestHeaders", "responseHeaders", "limits", "cache", "protection", "banDurations", "bandwidthLimit", "bodyCapture", "headerCapture", "cors"],
		properties: {
			requestHeaders: { $ref: "#/components/schemas/HeaderMutationPolicy" },
			responseHeaders: { $ref: "#/components/schemas/HeaderMutationPolicy" },
			limits: { $ref: "#/components/schemas/RouteRequestLimits" },
			cache: { $ref: "#/components/schemas/RouteStaticCachePolicy" },
			protection: { $ref: "#/components/schemas/RouteManagedProtectionPolicy" },
			banDurations: { $ref: "#/components/schemas/RouteBanDurationsPolicy" },
			bandwidthLimit: { $ref: "#/components/schemas/RouteBandwidthLimitPolicy" },
			bodyCapture: { $ref: "#/components/schemas/RouteBodyCapturePolicy" },
			headerCapture: { $ref: "#/components/schemas/RouteHeaderCapturePolicy" },
			cors: { $ref: "#/components/schemas/RouteCorsPolicy" },
		},
	},

	SiteWebSocketPolicy: {
		type: "object",
		required: ["mode", "available", "connectTimeoutMs", "idleTimeoutSeconds", "maxPayloadBytes", "preOpenQueueBytes", "upstreamBufferBytes"],
		properties: {
			mode: { type: "string", enum: ["allow", "deny"] },
			available: { type: "boolean", description: "Whether WebSocket support is enabled instance-wide; mode has no effect if this is false." },
			connectTimeoutMs: { type: "integer" },
			idleTimeoutSeconds: { type: "integer" },
			maxPayloadBytes: { type: "integer" },
			preOpenQueueBytes: { type: "integer" },
			upstreamBufferBytes: { type: "integer" },
		},
	},
	RouteWebSocketPolicy: {
		type: "object",
		description: "Any field left null inherits the site's value.",
		required: ["mode", "connectTimeoutMs", "idleTimeoutSeconds", "maxPayloadBytes", "preOpenQueueBytes", "upstreamBufferBytes"],
		properties: {
			mode: { type: "string", enum: ["inherit", "allow", "deny"] },
			connectTimeoutMs: { type: ["integer", "null"] },
			idleTimeoutSeconds: { type: ["integer", "null"] },
			maxPayloadBytes: { type: ["integer", "null"] },
			preOpenQueueBytes: { type: ["integer", "null"] },
			upstreamBufferBytes: { type: ["integer", "null"] },
		},
	},

	BotPolicy: {
		type: "object",
		required: ["blockedBots"],
		properties: {
			blockedBots: {
				type: "array",
				items: { type: "string" },
				description: "Bot catalog IDs to block, e.g. gptbot, ahrefsbot - see GET .../streams/protection-catalog for the full list.",
			},
		},
	},
	NetworkPrivacyPolicy: {
		type: "object",
		description: "Maps a network-privacy category id (e.g. tor, vpn, hosting) to a mode. Unlisted categories are not restricted.",
		additionalProperties: { type: "string", enum: ["disabled", "monitor", "block"] },
	},

	Origin: {
		type: "object",
		required: [
			"id",
			"name",
			"originType",
			"originUrl",
			"staticRoot",
			"staticIndexFile",
			"staticSpaFallback",
			"enabled",
			"draining",
			"priority",
			"weight",
			"healthCheckPath",
			"isPrimary",
			"mtls",
			"createdAt",
			"updatedAt",
		],
		properties: {
			id: { type: "string" },
			name: { type: "string", maxLength: 255 },
			originType: { type: "string", enum: ["proxy", "static"] },
			originUrl: { type: ["string", "null"], description: "Absolute http(s) URL. Set only when originType is proxy." },
			staticRoot: {
				type: ["string", "null"],
				description: "Absolute filesystem path under the configured static-sites root. Set only when originType is static.",
			},
			staticIndexFile: { type: ["string", "null"] },
			staticSpaFallback: { type: "boolean" },
			enabled: { type: "boolean" },
			draining: { type: "boolean", description: "When true, no new sessions are assigned to this origin, but existing ones continue." },
			priority: { type: "integer", minimum: 0, maximum: 10_000, description: "Lower is preferred for failover." },
			weight: { type: "integer", minimum: 1, maximum: 1000, description: "Relative share for weighted-round-robin." },
			healthCheckPath: { type: ["string", "null"] },
			isPrimary: { type: "boolean", description: "The primary origin cannot be deleted; edit it via the site instead." },
			mtls: {
				type: "object",
				required: ["enabled", "configured", "caConfigured"],
				properties: {
					enabled: { type: "boolean" },
					configured: { type: "boolean", description: "Whether a client certificate and private key are stored." },
					caConfigured: { type: "boolean", description: "Whether a CA bundle is stored to verify the origin's own server certificate." },
				},
			},
			createdAt: { type: "integer" },
			updatedAt: { type: "integer" },
		},
	},
	OriginInput: {
		type: "object",
		properties: {
			name: { type: "string", maxLength: 255 },
			originType: { type: "string", enum: ["proxy", "static"], default: "proxy" },
			originUrl: { type: "string", description: "Required when originType is proxy." },
			staticRoot: { type: "string", description: "Required when originType is static; must resolve inside the configured static-sites root." },
			staticIndexFile: { type: "string", default: "index.html" },
			staticSpaFallback: { type: "boolean", default: false },
			enabled: { type: "boolean", default: true },
			draining: { type: "boolean", default: false },
			priority: { type: "integer", minimum: 0, maximum: 10_000, default: 10 },
			weight: { type: "integer", minimum: 1, maximum: 1000, default: 1 },
			healthCheckPath: { type: ["string", "null"] },
			mtlsEnabled: { type: "boolean", default: false },
			mtlsCertificatePem: {
				type: "string",
				description: "PEM client certificate. Must be supplied together with mtlsPrivateKeyPem to replace the credential.",
			},
			mtlsPrivateKeyPem: { type: "string", description: "PEM private key, paired with mtlsCertificatePem." },
			mtlsCaPem: { type: "string", description: "PEM CA bundle used to verify the origin's own TLS certificate." },
		},
	},

	Site: {
		type: "object",
		required: [
			"id",
			"name",
			"publicHost",
			"originType",
			"originUrl",
			"staticRoot",
			"staticIndexFile",
			"staticSpaFallback",
			"ipExtractionPreset",
			"enabled",
			"sessionTtlSeconds",
			"challengePolicy",
			"challengeAutoBan",
			"defaultAccessMode",
			"eventRetentionDays",
			"defaultIpAction",
			"defaultCountryAction",
			"errorResponse",
			"challengePage",
			"healthCheck",
			"loadBalancer",
			"outboundFetchProtocol",
			"websocket",
			"http",
			"botPolicy",
			"networkPrivacyPolicy",
			"createdAt",
			"updatedAt",
		],
		properties: {
			id: { type: "string" },
			name: { type: "string", maxLength: 255 },
			publicHost: { type: "string", description: "Hostname, optionally with a port. Must be unique across all sites." },
			originType: { type: "string", enum: ["proxy", "static"] },
			originUrl: { type: ["string", "null"] },
			staticRoot: { type: ["string", "null"] },
			staticIndexFile: { type: ["string", "null"] },
			staticSpaFallback: { type: "boolean" },
			ipExtractionPreset: { type: "string", enum: ["direct", "cloudflare", "aws", "gcp", "azure", "vercel", "nginx", "development"] },
			enabled: { type: "boolean" },
			sessionTtlSeconds: { type: "integer", minimum: 60, maximum: 2_592_000 },
			challengePolicy: { type: "array", minItems: 1, maxItems: 16, items: { $ref: "#/components/schemas/ChallengePolicyStep" } },
			challengeAutoBan: {
				type: "object",
				required: ["enabled", "maxFailures", "banSeconds"],
				properties: {
					enabled: { type: "boolean" },
					maxFailures: { type: "integer", minimum: 1, maximum: 1000 },
					banSeconds: { type: "integer", minimum: 1, maximum: 2_592_000 },
				},
			},
			defaultAccessMode: { type: "string", enum: ["challenge", "bypass"] },
			eventRetentionDays: { type: "integer", minimum: 1, maximum: 365 },
			defaultIpAction: { type: "string", enum: ["inherit", "allow", "block", "challenge"] },
			defaultCountryAction: { type: "string", enum: ["inherit", "allow", "block", "challenge"] },
			errorResponse: {
				type: "object",
				required: ["mode", "htmlTemplate", "jsonFields"],
				properties: {
					mode: { type: "string", enum: ["html", "json"] },
					htmlTemplate: { type: "string" },
					jsonFields: { type: "array", items: { type: "string" } },
				},
			},
			challengePage: {
				type: "object",
				required: ["htmlTemplate", "templates", "textOverrides", "cspOverrides"],
				properties: {
					htmlTemplate: { type: "string" },
					templates: { type: "object", additionalProperties: { type: "string" }, description: "Per-provider HTML template override, keyed by provider id." },
					textOverrides: {
						type: "object",
						additionalProperties: { type: "object", additionalProperties: { type: "string" } },
						description: "Per-provider text-key overrides.",
					},
					cspOverrides: {
						type: "object",
						additionalProperties: { type: "object", additionalProperties: { type: "array", items: { type: "string" } } },
						description: "Per-provider Content-Security-Policy source-list overrides.",
					},
				},
			},
			healthCheck: {
				type: "object",
				required: ["enabled", "path", "intervalSeconds", "timeoutMs", "failureThreshold", "recoveryThreshold", "failureMode", "alerts"],
				properties: {
					enabled: { type: "boolean" },
					path: { type: "string" },
					intervalSeconds: { type: "integer", minimum: 3, maximum: 3600 },
					timeoutMs: { type: "integer", minimum: 250, maximum: 60_000 },
					failureThreshold: { type: "integer", minimum: 1, maximum: 20 },
					recoveryThreshold: { type: "integer", minimum: 1, maximum: 20 },
					failureMode: { type: "string", enum: ["monitor", "maintenance"] },
					alerts: {
						type: "object",
						required: ["enabled", "provider", "webhookConfigured", "eventTypes"],
						properties: {
							enabled: { type: "boolean" },
							provider: { type: "string", enum: ["generic", "slack", "discord", "ntfy"] },
							webhookConfigured: { type: "boolean" },
							eventTypes: { $ref: "#/components/schemas/NotificationEventTypeMap" },
						},
					},
				},
			},
			loadBalancer: {
				type: "object",
				required: ["algorithm", "affinity"],
				properties: {
					algorithm: { type: "string", enum: ["failover", "round-robin", "weighted-round-robin"] },
					affinity: { type: "boolean" },
				},
			},
			outboundFetchProtocol: { type: "string", enum: ["http1", "http2", "http3"] },
			websocket: { $ref: "#/components/schemas/SiteWebSocketPolicy" },
			http: { $ref: "#/components/schemas/SiteHttpPolicy" },
			botPolicy: { $ref: "#/components/schemas/BotPolicy" },
			networkPrivacyPolicy: { $ref: "#/components/schemas/NetworkPrivacyPolicy" },
			createdAt: { type: "integer" },
			updatedAt: { type: "integer" },
		},
	},
	NotificationEventTypeMap: {
		type: "object",
		description: "Whether each event type triggers a health-alert notification.",
		properties: Object.fromEntries(
			[
				"origin_unhealthy",
				"origin_recovered",
				"pool_unhealthy",
				"pool_recovered",
				"internet_down",
				"internet_up",
				"ip_banned",
				"stream_origin_unhealthy",
				"stream_origin_recovered",
				"stream_ip_banned",
				"system_resource_high",
				"system_resource_normal",
				"ha_node_down",
				"ha_node_up",
			].map((key) => [key, { type: "boolean" }]),
		),
	},
	SiteInput: {
		type: "object",
		description: "All fields are optional on update (existing values are kept); name, publicHost, and originUrl/staticRoot are required on create.",
		properties: {
			name: { type: "string", maxLength: 255 },
			publicHost: { type: "string" },
			originType: { type: "string", enum: ["proxy", "static"], default: "proxy" },
			originUrl: { type: "string" },
			staticRoot: { type: "string" },
			staticIndexFile: { type: "string" },
			staticSpaFallback: { type: "boolean" },
			enabled: { type: "boolean", default: true },
			sessionTtlSeconds: { type: "integer", minimum: 60, maximum: 2_592_000 },
			challengePolicy: { type: "array", minItems: 1, maxItems: 16, items: { $ref: "#/components/schemas/ChallengePolicyStep" } },
			challengeAutoBan: {
				type: "object",
				properties: {
					enabled: { type: "boolean" },
					maxFailures: { type: "integer", minimum: 1, maximum: 1000 },
					banSeconds: { type: "integer", minimum: 1, maximum: 2_592_000 },
				},
			},
			originSigningSecret: {
				type: "string",
				minLength: 32,
				maxLength: 512,
				description: "If omitted on create, one is generated and returned once as generatedSigningSecret.",
			},
			defaultAccessMode: { type: "string", enum: ["challenge", "bypass"] },
			eventRetentionDays: { type: "integer", minimum: 1, maximum: 365 },
			defaultIpAction: { type: "string", enum: ["inherit", "allow", "block", "challenge"] },
			defaultCountryAction: { type: "string", enum: ["inherit", "allow", "block", "challenge"] },
			errorResponseMode: { type: "string", enum: ["html", "json"] },
			errorHtmlTemplate: { type: "string" },
			challengeHtmlTemplate: { type: "string" },
			challengeHtmlTemplates: {
				type: "object",
				additionalProperties: { type: "string" },
				description: "Per-provider override; a blank value removes that provider's override.",
			},
			challengeTextOverrides: { type: "object", additionalProperties: { type: "object", additionalProperties: { type: "string" } } },
			challengeCspOverrides: { type: "object", additionalProperties: { type: "object", additionalProperties: { type: "string" } } },
			errorJsonFields: { type: "array", items: { type: "string" } },
			healthCheck: {
				type: "object",
				properties: {
					enabled: { type: "boolean" },
					path: { type: "string" },
					intervalSeconds: { type: "integer", minimum: 3, maximum: 3600 },
					timeoutMs: { type: "integer", minimum: 250, maximum: 60_000 },
					failureThreshold: { type: "integer", minimum: 1, maximum: 20 },
					recoveryThreshold: { type: "integer", minimum: 1, maximum: 20 },
					failureMode: { type: "string", enum: ["monitor", "maintenance"] },
					alerts: {
						type: "object",
						properties: {
							enabled: { type: "boolean" },
							provider: { type: "string", enum: ["generic", "slack", "discord", "ntfy"] },
							webhookUrl: { type: "string" },
							webhookSecret: { type: "string", maxLength: 4096 },
							clearWebhook: { type: "boolean", default: false },
							eventTypes: { $ref: "#/components/schemas/NotificationEventTypeMap" },
						},
					},
				},
			},
			loadBalancer: {
				type: "object",
				properties: { algorithm: { type: "string", enum: ["failover", "round-robin", "weighted-round-robin"] }, affinity: { type: "boolean" } },
			},
			outboundFetchProtocol: { type: "string", enum: ["http1", "http2", "http3"] },
			ipExtractionPreset: { type: "string", enum: ["direct", "cloudflare", "aws", "gcp", "azure", "vercel", "nginx", "development"] },
			websocket: { $ref: "#/components/schemas/SiteWebSocketPolicyInput" },
			http: { $ref: "#/components/schemas/SiteHttpPolicyInput" },
			botPolicy: { $ref: "#/components/schemas/BotPolicy" },
			networkPrivacyPolicy: { $ref: "#/components/schemas/NetworkPrivacyPolicy" },
			effectiveAt: {
				type: "integer",
				description:
					"Unix milliseconds. If set and this update changes the public hostname while TLS is active, the change is scheduled instead of applied immediately.",
			},
		},
	},
	SiteWebSocketPolicyInput: {
		type: "object",
		description: "Partial update; omitted fields keep their current value. Each numeric field is bounded by the instance's own configured WebSocket limits.",
		properties: {
			mode: { type: "string", enum: ["allow", "deny"] },
			connectTimeoutMs: { type: "integer" },
			idleTimeoutSeconds: { type: "integer" },
			maxPayloadBytes: { type: "integer" },
			preOpenQueueBytes: { type: "integer" },
			upstreamBufferBytes: { type: "integer" },
		},
	},
	SiteHttpPolicyInput: {
		type: "object",
		description: "Partial update; every sub-object merges onto the current stored policy field-by-field, so omitted fields keep their current value.",
		properties: {
			requestHeaders: { $ref: "#/components/schemas/HeaderMutationPolicy" },
			responseHeaders: { $ref: "#/components/schemas/HeaderMutationPolicy" },
			limits: { $ref: "#/components/schemas/RequestLimits" },
			cache: { $ref: "#/components/schemas/SiteStaticCachePolicy" },
			protection: { $ref: "#/components/schemas/SiteManagedProtectionPolicy" },
			banDurations: { $ref: "#/components/schemas/SiteBanDurationsPolicy" },
			bandwidthLimit: { $ref: "#/components/schemas/SiteBandwidthLimitPolicy" },
			bodyCapture: { $ref: "#/components/schemas/SiteBodyCapturePolicy" },
			headerCapture: { $ref: "#/components/schemas/SiteHeaderCapturePolicy" },
			cors: { $ref: "#/components/schemas/SiteCorsPolicy" },
			hsts: { $ref: "#/components/schemas/SiteHstsPolicy" },
		},
	},

	RouteIpRule: {
		type: "object",
		required: ["id", "route_policy_id", "network_cidr", "action", "reason", "created_at", "expires_at"],
		description: "Returned as a raw row (snake_case), not through a camelCase view.",
		properties: {
			id: { type: "string" },
			route_policy_id: { type: "string" },
			network_cidr: { type: "string" },
			action: { type: "string", enum: ["allow", "pass", "block", "challenge"] },
			reason: { type: "string" },
			created_at: { type: "integer" },
			expires_at: { type: ["integer", "null"] },
		},
	},
	RouteIpRuleInput: {
		type: "object",
		required: ["networkCidr", "action"],
		properties: {
			networkCidr: { type: "string" },
			action: { type: "string", enum: ["allow", "pass", "block", "challenge"] },
			reason: { type: "string" },
			expiresAt: { type: ["integer", "string", "null"], description: "Unix milliseconds in the future, or null for no expiry." },
		},
	},
	RouteCountryRule: {
		type: "object",
		required: ["id", "route_policy_id", "country_code", "action", "reason", "created_at", "expires_at"],
		description: "Returned as a raw row (snake_case), not through a camelCase view.",
		properties: {
			id: { type: "string" },
			route_policy_id: { type: "string" },
			country_code: { type: "string" },
			action: { type: "string", enum: ["allow", "pass", "block", "challenge"] },
			reason: { type: "string" },
			created_at: { type: "integer" },
			expires_at: { type: ["integer", "null"] },
		},
	},
	RouteCountryRuleInput: {
		type: "object",
		required: ["countryCode", "action"],
		properties: {
			countryCode: { type: "string" },
			action: { type: "string", enum: ["allow", "pass", "block", "challenge"] },
			reason: { type: "string" },
			expiresAt: { type: ["integer", "string", "null"] },
		},
	},
	RouteAsnRule: {
		type: "object",
		required: ["id", "route_policy_id", "asn", "action", "reason", "created_at", "expires_at"],
		description: "Returned as a raw row (snake_case), not through a camelCase view.",
		properties: {
			id: { type: "string" },
			route_policy_id: { type: "string" },
			asn: { type: "integer" },
			action: { type: "string", enum: ["allow", "pass", "block", "challenge"] },
			reason: { type: "string" },
			created_at: { type: "integer" },
			expires_at: { type: ["integer", "null"] },
		},
	},
	RouteAsnRuleInput: {
		type: "object",
		required: ["asn", "action"],
		properties: {
			asn: { type: ["integer", "string"] },
			action: { type: "string", enum: ["allow", "pass", "block", "challenge"] },
			reason: { type: "string" },
			expiresAt: { type: ["integer", "string", "null"] },
		},
	},

	OriginHealthSummary: {
		type: "object",
		description: "Live health summary for a site's origin pool.",
		additionalProperties: true,
	},
	OriginHealthEvent: { type: "object", additionalProperties: true, description: "A recorded origin health state-change event." },
	OriginBackendHealthEvent: {
		allOf: [{ type: "object", additionalProperties: true }],
		type: "object",
		description: "A recorded per-backend health event, with the origin's name resolved onto it.",
		properties: { originName: { type: "string" } },
	},
	StaticRootListing: {
		type: "object",
		description: "A jailed directory listing under the instance's configured static-sites root, used to build a folder picker.",
		required: ["relativePath", "parentPath", "rootDirectory", "entries"],
		properties: {
			relativePath: { type: "string" },
			parentPath: { type: ["string", "null"] },
			rootDirectory: { type: "string" },
			entries: {
				type: "array",
				items: {
					type: "object",
					required: ["name", "relativePath", "hasIndexFile"],
					properties: { name: { type: "string" }, relativePath: { type: "string" }, hasIndexFile: { type: "boolean" } },
				},
			},
		},
	},
	SiteNotificationOutboxItem: {
		type: "object",
		required: ["id", "type", "severity", "summary", "status", "attempts", "lastError", "occurredAt", "createdAt", "deliveredAt"],
		properties: {
			id: { type: "string" },
			type: { type: "string" },
			severity: { type: "string" },
			summary: { type: "string" },
			status: { type: "string", enum: ["pending", "delivered", "failed"] },
			attempts: { type: "integer" },
			lastError: { type: ["string", "null"] },
			occurredAt: { type: "integer" },
			createdAt: { type: "integer" },
			deliveredAt: { type: ["integer", "null"] },
		},
	},

	RoutePolicy: {
		type: "object",
		required: [
			"id",
			"siteId",
			"name",
			"pathPattern",
			"methods",
			"accessMode",
			"challengePolicy",
			"rateLimit",
			"websocket",
			"http",
			"defaultIpAction",
			"defaultCountryAction",
			"botPolicy",
			"networkPrivacyPolicy",
			"priority",
			"enabled",
			"createdAt",
			"updatedAt",
		],
		properties: {
			id: { type: "string" },
			siteId: { type: "string" },
			name: { type: "string", maxLength: 255 },
			pathPattern: {
				type: "string",
				maxLength: 2048,
				description: "Must start with /. Supports * (single path segment) and a trailing /** (this path and everything under it).",
			},
			methods: {
				type: "array",
				items: { type: "string", enum: ["GET", "HEAD", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"] },
				description: "Empty array matches every method.",
			},
			accessMode: { type: "string", enum: ["inherit", "challenge", "bypass", "block"] },
			challengePolicy: {
				oneOf: [{ type: "null" }, { type: "array", minItems: 1, maxItems: 16, items: { $ref: "#/components/schemas/ChallengePolicyStep" } }],
				description: "null inherits the site's challenge chain.",
			},
			rateLimit: {
				type: "object",
				required: ["enabled", "algorithm", "windowMs", "max", "refillRate", "refillIntervalMs", "precisionMs", "keyMode", "keyHeader", "scope"],
				properties: {
					enabled: { type: "boolean" },
					algorithm: { type: "string", enum: ["fixed-window", "sliding-window", "token-bucket"] },
					windowMs: { type: "integer", minimum: 100, maximum: 86_400_000 },
					max: { type: "integer", minimum: 1, maximum: 1_000_000 },
					refillRate: { type: "integer", minimum: 1, maximum: 1_000_000, description: "token-bucket only: tokens added per refill interval." },
					refillIntervalMs: { type: "integer", minimum: 10, maximum: 86_400_000 },
					precisionMs: { type: "integer", minimum: 10, maximum: 60_000, description: "sliding-window only: bucket resolution." },
					keyMode: { type: "string", enum: ["ip", "session-or-ip", "header-or-ip"] },
					keyHeader: { type: ["string", "null"], description: "Required (and only used) when keyMode is header-or-ip." },
					scope: { type: "string", enum: ["policy", "path", "method-path"] },
				},
			},
			websocket: { $ref: "#/components/schemas/RouteWebSocketPolicy" },
			http: { $ref: "#/components/schemas/RouteHttpPolicy" },
			defaultIpAction: { type: "string", enum: ["inherit", "allow", "block", "challenge"] },
			defaultCountryAction: { type: "string", enum: ["inherit", "allow", "block", "challenge"] },
			botPolicy: { oneOf: [{ type: "null" }, { $ref: "#/components/schemas/BotPolicy" }], description: "null inherits the site's bot policy." },
			networkPrivacyPolicy: {
				oneOf: [{ type: "null" }, { $ref: "#/components/schemas/NetworkPrivacyPolicy" }],
				description: "null inherits the site's policy.",
			},
			priority: { type: "integer", minimum: -100_000, maximum: 100_000, description: "Higher wins when multiple route policies match the same request." },
			enabled: { type: "boolean" },
			createdAt: { type: "integer" },
			updatedAt: { type: "integer" },
		},
	},
	RoutePolicyInput: {
		type: "object",
		description: "All fields are optional on update (existing values are kept); name, pathPattern are required on create.",
		properties: {
			name: { type: "string", maxLength: 255 },
			pathPattern: { type: "string", maxLength: 2048 },
			methods: {
				oneOf: [
					{ type: "array", items: { type: "string" } },
					{ type: "string", description: "Comma-separated methods." },
				],
				description: "Empty, `*`, or omitted matches every method.",
			},
			accessMode: { type: "string", enum: ["inherit", "challenge", "bypass", "block"], default: "inherit" },
			challengePolicy: {
				oneOf: [{ type: "null" }, { type: "array", minItems: 1, maxItems: 16, items: { $ref: "#/components/schemas/ChallengePolicyStep" } }],
			},
			rateLimitEnabled: { type: "boolean", default: false },
			rateLimitAlgorithm: { type: "string", enum: ["fixed-window", "sliding-window", "token-bucket"], default: "sliding-window" },
			rateLimitWindowMs: { type: "integer", minimum: 100, maximum: 86_400_000, default: 60_000 },
			rateLimitMax: { type: "integer", minimum: 1, maximum: 1_000_000, default: 120 },
			rateLimitRefillRate: { type: "integer", minimum: 1, maximum: 1_000_000, default: 10 },
			rateLimitRefillIntervalMs: { type: "integer", minimum: 10, maximum: 86_400_000, default: 1000 },
			rateLimitPrecisionMs: { type: "integer", minimum: 10, maximum: 60_000, default: 100 },
			rateLimitKeyMode: { type: "string", enum: ["ip", "session-or-ip", "header-or-ip"], default: "ip" },
			rateLimitKeyHeader: { type: "string", maxLength: 128, description: "Required when rateLimitKeyMode is header-or-ip." },
			rateLimitScope: { type: "string", enum: ["policy", "path", "method-path"], default: "policy" },
			priority: { type: "integer", minimum: -100_000, maximum: 100_000, default: 0 },
			enabled: { type: "boolean", default: true },
			websocket: { $ref: "#/components/schemas/RouteWebSocketPolicyInput" },
			http: { $ref: "#/components/schemas/RouteHttpPolicyInput" },
			defaultIpAction: { type: "string", enum: ["inherit", "allow", "block", "challenge"], default: "inherit" },
			defaultCountryAction: { type: "string", enum: ["inherit", "allow", "block", "challenge"], default: "inherit" },
			botPolicy: { oneOf: [{ type: "null" }, { $ref: "#/components/schemas/BotPolicy" }] },
			networkPrivacyPolicy: { oneOf: [{ type: "null" }, { $ref: "#/components/schemas/NetworkPrivacyPolicy" }] },
		},
	},
	RouteWebSocketPolicyInput: {
		type: "object",
		properties: {
			mode: { type: "string", enum: ["inherit", "allow", "deny"] },
			connectTimeoutMs: { type: ["integer", "null"] },
			idleTimeoutSeconds: { type: ["integer", "null"] },
			maxPayloadBytes: { type: ["integer", "null"] },
			preOpenQueueBytes: { type: ["integer", "null"] },
			upstreamBufferBytes: { type: ["integer", "null"] },
		},
	},
	RouteHttpPolicyInput: {
		type: "object",
		description: "Partial update; every sub-object merges onto the current stored policy field-by-field.",
		properties: {
			requestHeaders: { $ref: "#/components/schemas/HeaderMutationPolicy" },
			responseHeaders: { $ref: "#/components/schemas/HeaderMutationPolicy" },
			limits: { $ref: "#/components/schemas/RouteRequestLimits" },
			cache: { $ref: "#/components/schemas/RouteStaticCachePolicy" },
			protection: { $ref: "#/components/schemas/RouteManagedProtectionPolicy" },
			banDurations: { $ref: "#/components/schemas/RouteBanDurationsPolicy" },
			bandwidthLimit: { $ref: "#/components/schemas/RouteBandwidthLimitPolicy" },
			bodyCapture: { $ref: "#/components/schemas/RouteBodyCapturePolicy" },
			headerCapture: { $ref: "#/components/schemas/RouteHeaderCapturePolicy" },
			cors: { $ref: "#/components/schemas/RouteCorsPolicy" },
		},
	},
};
