import { ref } from "./types.ts";
import type { JsonSchema } from "./types.ts";

export const metricsSchemas: Record<string, JsonSchema> = {
	RequestEvent: {
		type: "object",
		description:
			"A single captured request/response, as returned by GET /events and GET /events/{id}. protection_matches and network_privacy are derived " +
			"at response time by parsing protection_matches_json/network_privacy_json (both raw fields are also included, unparsed).",
		required: [
			"id",
			"site_id",
			"session_id",
			"ip",
			"method",
			"path",
			"status",
			"decision",
			"latency_ms",
			"country_code",
			"asn",
			"asn_org",
			"cache_status",
			"protection_status",
			"protection_rule_id",
			"protection_category",
			"protection_severity",
			"protection_ruleset_id",
			"protection_ruleset_version",
			"protection_matches_json",
			"protection_matches",
			"access_username",
			"referer",
			"referer_host",
			"network_privacy",
			"request_body",
			"request_body_truncated",
			"request_content_type",
			"response_body",
			"response_body_truncated",
			"response_content_type",
			"request_headers",
			"request_headers_truncated",
			"response_headers",
			"response_headers_truncated",
			"created_at",
			"origin_name",
		],
		properties: {
			id: { type: "string" },
			site_id: { type: "string" },
			session_id: { type: ["string", "null"] },
			ip: { type: "string" },
			method: { type: "string" },
			path: { type: "string" },
			status: { type: "integer" },
			decision: {
				type: "string",
				description: "Free-text decision label, e.g. verified, blocked, route-blocked, bot-blocked, challenge-required, rate-limited, access-authenticated.",
			},
			latency_ms: { type: "number" },
			country_code: { type: ["string", "null"] },
			asn: { type: ["integer", "null"] },
			asn_org: { type: ["string", "null"] },
			origin_id: { type: ["string", "null"] },
			origin_name: { type: ["string", "null"], description: "Resolved from origin_id; null if the event has no origin or the origin was deleted." },
			cache_status: { type: ["string", "null"], enum: ["hit", "miss", "bypass", null] },
			protection_status: { type: ["string", "null"], enum: ["clean", "monitored", "blocked", null] },
			protection_rule_id: { type: ["string", "null"] },
			protection_category: { type: ["string", "null"] },
			protection_severity: { type: ["string", "null"] },
			protection_ruleset_id: { type: ["string", "null"] },
			protection_ruleset_version: { type: ["string", "null"] },
			protection_matches_json: {
				type: ["string", "null"],
				description: "Raw JSON array of matched managed-protection rules; see protection_matches for the parsed form.",
			},
			protection_matches: {
				type: "array",
				items: { type: "object", additionalProperties: true },
				description: "protection_matches_json, parsed (empty array if unparsable).",
			},
			access_username: { type: ["string", "null"] },
			referer: { type: ["string", "null"] },
			referer_host: { type: ["string", "null"] },
			bot_id: { type: ["string", "null"] },
			bot_name: { type: ["string", "null"] },
			bot_category: { type: ["string", "null"] },
			bot_verified: { type: ["integer", "null"] },
			network_privacy_json: {
				type: ["string", "null"],
				description: "Raw JSON array of matched network-privacy categories; see network_privacy for the parsed form.",
			},
			network_privacy: { type: "array", items: { type: "string" }, description: "network_privacy_json, parsed (empty array if unparsable)." },
			request_body: { type: ["string", "null"] },
			request_body_truncated: { type: ["integer", "null"] },
			request_content_type: { type: ["string", "null"] },
			response_body: { type: ["string", "null"] },
			response_body_truncated: { type: ["integer", "null"] },
			response_content_type: { type: ["string", "null"] },
			request_headers: { type: ["string", "null"], description: "Raw captured request headers, one per line as name: value." },
			request_headers_truncated: { type: ["integer", "null"] },
			response_headers: { type: ["string", "null"] },
			response_headers_truncated: { type: ["integer", "null"] },
			created_at: { type: "integer", description: "Unix milliseconds." },
		},
	},

	ResendHop: {
		type: "object",
		description: "One HTTP hop of a resend attempt (src/services/resend-service.ts).",
		required: ["method", "path", "status", "location", "followed", "notFollowedReason"],
		properties: {
			method: { type: "string" },
			path: { type: "string" },
			status: { type: "integer" },
			location: { type: ["string", "null"], description: "The Location response header on this hop, if any." },
			followed: { type: "boolean" },
			notFollowedReason: { type: ["string", "null"], enum: ["off-site", "redirect-limit", "no-location", "unparseable-location", null] },
		},
	},
	ResendResult: {
		type: "object",
		description: "Result of POST /events/{id}/resend. Redirects are followed automatically up to 10 hops, only while staying on the site's own hostname.",
		required: ["status", "headers", "body", "bodyTruncated", "hops"],
		properties: {
			status: { type: "integer", description: "HTTP status of the final hop." },
			headers: {
				type: "array",
				description: "Response headers of the final hop, as [name, value] pairs.",
				items: { type: "array", minItems: 2, maxItems: 2, items: { type: "string" } },
			},
			body: { type: "string", description: "Response body of the final hop, capped at 64KiB." },
			bodyTruncated: { type: "boolean" },
			hops: { type: "array", items: ref("ResendHop") },
		},
	},

	IpRule: {
		type: "object",
		description: "A site-level IP/CIDR rule (src/services/ip-rule-service.ts).",
		required: ["id", "site_id", "network_cidr", "action", "reason", "created_at", "expires_at", "rule_id"],
		properties: {
			id: { type: "string" },
			site_id: { type: "string" },
			network_cidr: { type: "string", description: "A single IP address or CIDR block." },
			action: { type: "string", enum: ["allow", "pass", "block", "challenge"] },
			reason: { type: "string" },
			created_at: { type: "integer" },
			expires_at: { type: ["integer", "null"] },
			rule_id: {
				type: ["string", "null"],
				description: "Set when this rule was created automatically by a violation (e.g. auto-ban), referencing the triggering rule.",
			},
		},
	},
	CountryRule: {
		type: "object",
		description: "A site-level country rule. At most one active rule per country code per site.",
		required: ["id", "site_id", "country_code", "action", "reason", "created_at", "expires_at"],
		properties: {
			id: { type: "string" },
			site_id: { type: "string" },
			country_code: { type: "string", pattern: "^[A-Z]{2}$" },
			action: { type: "string", enum: ["allow", "pass", "block", "challenge"] },
			reason: { type: "string" },
			created_at: { type: "integer" },
			expires_at: { type: ["integer", "null"] },
		},
	},
	AsnRule: {
		type: "object",
		description: "A site-level ASN rule. At most one active rule per ASN per site.",
		required: ["id", "site_id", "asn", "action", "reason", "created_at", "expires_at"],
		properties: {
			id: { type: "string" },
			site_id: { type: "string" },
			asn: { type: "integer", minimum: 1 },
			action: { type: "string", enum: ["allow", "pass", "block", "challenge"] },
			reason: { type: "string" },
			created_at: { type: "integer" },
			expires_at: { type: ["integer", "null"] },
		},
	},

	AccessSession: {
		type: "object",
		description: "A visitor session (access-list authenticated or anonymous), as returned by GET /sessions.",
		required: [
			"id",
			"site_id",
			"token_hash",
			"initial_ip",
			"last_ip",
			"user_agent_hash",
			"created_at",
			"last_seen_at",
			"expires_at",
			"revoked_at",
			"verification_summary_json",
			"request_count",
			"country_code",
			"asn",
			"asn_org",
			"access_user_id",
			"authenticated_at",
			"sso_sid",
			"access_username",
		],
		properties: {
			id: { type: "string" },
			site_id: { type: "string" },
			token_hash: { type: "string", description: "SHA-256 hash of the session token; the plaintext token is never stored." },
			initial_ip: { type: "string" },
			last_ip: { type: "string" },
			user_agent_hash: { type: "string" },
			created_at: { type: "integer" },
			last_seen_at: { type: "integer" },
			expires_at: { type: "integer" },
			revoked_at: { type: ["integer", "null"] },
			verification_summary_json: { type: "string", description: "Raw JSON summary of which challenge steps this session has verified." },
			request_count: { type: "integer" },
			country_code: { type: ["string", "null"] },
			asn: { type: ["integer", "null"] },
			asn_org: { type: ["string", "null"] },
			access_user_id: { type: ["string", "null"] },
			authenticated_at: { type: ["integer", "null"] },
			origin_id: { type: ["string", "null"] },
			sso_sid: { type: ["string", "null"] },
			access_username: { type: ["string", "null"], description: "Joined from the access user, if any; null for an anonymous session." },
		},
	},

	BandwidthIpRow: {
		type: "object",
		description: "Aggregated client/upstream bandwidth for one IP address over the selected range.",
		required: [
			"ip",
			"country_code",
			"client_received_bytes",
			"client_sent_bytes",
			"upstream_sent_bytes",
			"upstream_received_bytes",
			"client_total_bytes",
			"upstream_total_bytes",
		],
		properties: {
			ip: { type: "string" },
			country_code: { type: "string" },
			client_received_bytes: {
				type: ["integer", "string"],
				description: "Bytes BurrowGate received from clients. A string for values exceeding safe-integer precision.",
			},
			client_sent_bytes: { type: ["integer", "string"] },
			upstream_sent_bytes: { type: ["integer", "string"] },
			upstream_received_bytes: { type: ["integer", "string"] },
			client_total_bytes: { type: ["integer", "string"] },
			upstream_total_bytes: { type: ["integer", "string"] },
		},
	},

	MetricsPageEnvelope: {
		type: "object",
		required: ["page", "pageSize", "total", "totalPages"],
		properties: {
			page: { type: "integer", minimum: 1 },
			pageSize: { type: "integer", minimum: 1, maximum: 200 },
			total: { type: "integer" },
			totalPages: { type: "integer" },
		},
	},

	UpdateCheckStatus: {
		type: "object",
		required: ["checkedAt", "currentVersion", "latestVersion", "updateAvailable", "releaseName", "releaseNotes", "releaseUrl", "publishedAt", "error"],
		properties: {
			checkedAt: { type: ["integer", "null"], description: "Unix milliseconds of the last check, or null if none has run yet." },
			currentVersion: { type: "string" },
			latestVersion: { type: ["string", "null"] },
			updateAvailable: { type: "boolean" },
			releaseName: { type: ["string", "null"] },
			releaseNotes: { type: ["string", "null"] },
			releaseUrl: { type: ["string", "null"] },
			publishedAt: { type: ["string", "null"], description: "ISO 8601 timestamp." },
			error: { type: ["string", "null"] },
		},
	},

	MetricsOverview: {
		type: "object",
		description: "Instance- or site-scoped headline counters for the dashboard's overview cards.",
		required: [
			"activeSessions",
			"activeRules",
			"cacheHitRatio",
			"blocked24h",
			"requests24h",
			"challenges24h",
			"errors24h",
			"uniqueIps24h",
			"averageLatency24h",
			"errorRate24h",
			"rangeFrom",
			"rangeTo",
			"rangeDurationMs",
		],
		properties: {
			activeSessions: { type: "integer" },
			activeRules: { type: "integer", description: "Sum of active (unexpired) IP, country, and ASN rules." },
			cacheHitRatio: { type: "number", description: "0-1; hits / (hits + misses) over the range." },
			blocked24h: { type: "integer", description: "Named for the default 24h range; reflects whatever range was requested." },
			requests24h: { type: "integer" },
			challenges24h: { type: "integer" },
			errors24h: { type: "integer", description: "5xx responses." },
			uniqueIps24h: { type: "integer" },
			averageLatency24h: { type: "integer", description: "Milliseconds, rounded." },
			errorRate24h: { type: "number", description: "Percentage (0-100), rounded to 2 decimals." },
			rangeFrom: { type: "integer" },
			rangeTo: { type: "integer" },
			rangeDurationMs: { type: "integer" },
		},
	},

	GeoMetricRow: { type: "object", required: ["countryCode", "count"], properties: { countryCode: { type: "string" }, count: { type: "integer" } } },
	AsnMetricRow: {
		type: "object",
		required: ["asn", "org", "count"],
		properties: { asn: { type: "integer" }, org: { type: "string" }, count: { type: "integer" } },
	},
	RefererMetricRow: { type: "object", required: ["refererHost", "count"], properties: { refererHost: { type: "string" }, count: { type: "integer" } } },
	BotMetricRow: {
		type: "object",
		required: ["botId", "name", "category", "verified", "count"],
		properties: {
			botId: { type: "string" },
			name: { type: "string" },
			category: { type: "string" },
			verified: { type: "boolean", description: "Whether the bot's claimed identity was verified against its published IP ranges." },
			count: { type: "integer" },
		},
	},
	IpMetricRow: { type: "object", required: ["ip", "count"], properties: { ip: { type: "string" }, count: { type: "integer" } } },
	PathMetricRow: { type: "object", required: ["path", "count"], properties: { path: { type: "string" }, count: { type: "integer" } } },
	UsernameMetricRow: { type: "object", required: ["username", "count"], properties: { username: { type: "string" }, count: { type: "integer" } } },

	MetricsChartDataset: {
		type: "object",
		required: ["key", "label"],
		properties: { key: { type: "string", description: "Property name to read from each entry in the sibling `data` array." }, label: { type: "string" } },
	},
	MetricsChartSeries: {
		type: "object",
		description: "One chart (a `primary`, `secondary`, or named extra chart) within a GET /metrics response.",
		required: ["title", "subtitle", "type", "timeSeries", "valueFormat", "emptyMessage", "datasets", "data"],
		properties: {
			title: { type: "string" },
			subtitle: { type: "string" },
			type: { type: "string", enum: ["line", "bar"] },
			timeSeries: { type: "boolean", description: "When true, each `data` entry has a `bucket` (unix ms) field in addition to the dataset keys." },
			valueFormat: { type: "string", enum: ["number", "duration", "percentage", "bytes", "bitrate"] },
			emptyMessage: { type: "string", description: "Shown by the dashboard when `data` is empty." },
			datasets: { type: "array", items: ref("MetricsChartDataset") },
			data: {
				type: "array",
				items: {
					type: "object",
					additionalProperties: true,
					description: "Keyed by each dataset's `key` (plus `bucket` when timeSeries), or by `label`/`count` for a non-time-series bar chart.",
				},
			},
		},
	},
	MetricsBreakdownItem: {
		type: "object",
		required: ["label", "count"],
		properties: { label: { type: "string" }, count: { type: "number" } },
	},
	MetricsChartResponse: {
		type: "object",
		description:
			"Response of GET /metrics. Fields common to every `section` are listed below; each section additionally attaches its own extra top-level " +
			"fields (for example `cache`, `protection`, `rulesets`, `bots`, `protocols`, or `methods`) whose exact shape varies by section - see the " +
			"~620-line handler in src/routes/admin-routes.ts for the section actually requested. `primary` is omitted for the four system-resource " +
			"sections (they only populate `secondary`).",
		required: ["section", "rangeFrom", "rangeTo", "rangeDurationMs", "bucketMs", "bucketCount", "breakdown"],
		properties: {
			section: {
				type: "string",
				enum: [
					"traffic",
					"bandwidth",
					"cache",
					"protection",
					"bots",
					"sessions",
					"rules",
					"routes",
					"access",
					"sites",
					"connectivity",
					"health",
					"system-cpu",
					"system-memory",
					"system-disk",
					"system-network-download",
					"system-network-upload",
				],
			},
			rangeFrom: { type: "integer" },
			rangeTo: { type: "integer" },
			rangeDurationMs: { type: "integer" },
			bucketMs: { type: "integer", description: "Auto-selected bucket width for the requested range, from a fixed ladder between 1 minute and 1 week." },
			bucketCount: { type: "integer" },
			primary: ref("MetricsChartSeries"),
			secondary: ref("MetricsChartSeries"),
			breakdown: {
				type: "array",
				items: ref("MetricsBreakdownItem"),
				description: "Small summary list; empty array for a few sections (health, rules, routes) that present their totals elsewhere.",
			},
		},
		additionalProperties: true,
	},
};
